-- 更新设备类型编码的 SQL 语句
-- 执行前请备份 assets.db 数据库

-- 1. 型号:ZTEM6000-S, 编码OTHER改为SWITCH_ZTE
UPDATE DEVICE_TYPE_TAB SET DEVICE = 'SWITCH_ZTE' WHERE RULE LIKE '%ZTEM6000%' AND DEVICE = 'OTHER';

-- 2. 型号:QorlQ SDK (FSL Reference Distro)1.9, 编码OS REDHAT改为SWITCH OTHER
UPDATE DEVICE_TYPE_TAB SET DEVICE = 'SWITCH_OTHER' WHERE RULE LIKE '%QorIQ%' AND DEVICE = 'OS_REDHAT';

-- 3. 型号:H3C SecPath M9008-S、H3CSecPath M9008-S-V，编码SWITCH H3C改为FIREWALL H3C
UPDATE DEVICE_TYPE_TAB SET DEVICE = 'FIREWALL_H3C' WHERE RULE LIKE '%H3C SecPath M9008%' AND DEVICE = 'SWITCH_H3C';
UPDATE DEVICE_TYPE_TAB SET DEVICE = 'FIREWALL_H3C' WHERE RULE LIKE '%H3CSecPath M9008%' AND DEVICE = 'SWITCH_H3C';

-- 4. 型号:H3C SecPath L5000-E，编码OS_H3C改为FIREWALL_H3C
UPDATE DEVICE_TYPE_TAB SET DEVICE = 'FIREWALL_H3C' WHERE RULE LIKE '%H3C SecPath L5000%' AND DEVICE = 'OS_H3C';

-- 5. 型号:Quidway S9306 Terabit Routing Switch，编码SWITCH_HUAWEI改为SWITCH_H3C
UPDATE DEVICE_TYPE_TAB SET DEVICE = 'SWITCH_H3C' WHERE RULE LIKE '%Quidway S9306%' AND DEVICE = 'SWITCH_HUAWEI';

-- 6. 型号:H3C SecPathM9006，编码SWITCH_H3C改为FIREWALL_H3C
UPDATE DEVICE_TYPE_TAB SET DEVICE = 'FIREWALL_H3C' WHERE RULE LIKE '%H3C SecPathM9006%' AND DEVICE = 'SWITCH_H3C';
