/* Layout */
import Layout from "@/layout";
import Parent from "@/layout/components/ParentView";

const examplesRoutes = [
  {
    path: "/ziChanXinXiShangBaoTiaoZheng",
    name: "资产信息上报调整",
    meta: { title: "资产信息上报调整", icon: "setting" },
    component: Layout,
    children: [
    
    // ─── JL吉林COSMIC（自动生成）───
    {
      path: "JLJiLinCOSMIC",
      name: "JL吉林COSMIC",
      meta: { title: "JL吉林COSMIC" },
      component: Parent,
      children: [
        {
          path: "IPSaoMiaoZhiLingXiaFaJieKou",
          name: "IP扫描指令下发接口-4-142-1",
          meta: { title: "IP扫描指令下发接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP扫描指令下发接口/index"),
        },
        {
          path: "ZhiLingJieShouRenWuDiaoDuGuanLi",
          name: "指令接收任务调度管理-4-142-2",
          meta: { title: "指令接收任务调度管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/指令接收任务调度管理/index"),
        },
        {
          path: "IPSaoMiaoZhiLingJieShouGuanLi",
          name: "IP扫描指令接收管理-4-142-3",
          meta: { title: "IP扫描指令接收管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP扫描指令接收管理/index"),
        },
        {
          path: "IPSaoMiaoZhiLingFanKuiJieKou",
          name: "IP扫描指令反馈接口-4-142-4",
          meta: { title: "IP扫描指令反馈接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP扫描指令反馈接口/index"),
        },
        {
          path: "SaoMiaoRenWuJieShouGuanLi",
          name: "扫描任务接收管理-4-142-5",
          meta: { title: "扫描任务接收管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描任务接收管理/index"),
        },
        {
          path: "LianDongZhiLingKongZhiGuanLi",
          name: "联动指令控制管理-4-142-6",
          meta: { title: "联动指令控制管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/联动指令控制管理/index"),
        },
        {
          path: "IPSaoMiaoRenWuFenFaLiuChengGuanLi",
          name: "IP扫描任务分发流程管理-4-142-7",
          meta: { title: "IP扫描任务分发流程管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP扫描任务分发流程管理/index"),
        },
        {
          path: "JieShouZhuangTaiFanKuiGuanLi",
          name: "接收状态反馈管理-4-142-8",
          meta: { title: "接收状态反馈管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/接收状态反馈管理/index"),
        },
        {
          path: "ZhiLingFanKuiZhuangTaiTongBuJieKou",
          name: "指令反馈状态同步接口-4-142-9",
          meta: { title: "指令反馈状态同步接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/指令反馈状态同步接口/index"),
        },
        {
          path: "FanKuiZiChanZhuangTaiJianKong",
          name: "反馈资产状态监控-4-142-10",
          meta: { title: "反馈资产状态监控" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/反馈资产状态监控/index"),
        },
        {
          path: "ZhiLingFanKuiChaoShiYuJingGuanLi",
          name: "指令反馈超时预警管理-4-142-11",
          meta: { title: "指令反馈超时预警管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/指令反馈超时预警管理/index"),
        },
        {
          path: "FanKuiZiChanWanZhengXingJiaoYanGuanLi",
          name: "反馈资产完整性校验管理-4-142-12",
          meta: { title: "反馈资产完整性校验管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/反馈资产完整性校验管理/index"),
        },
        {
          path: "GongXinBuLianDongSaoMiaoRenWuGuanLi",
          name: "工信部联动扫描任务管理-4-142-13",
          meta: { title: "工信部联动扫描任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/工信部联动扫描任务管理/index"),
        },
        {
          path: "BuCeIPV4SaoMiaoLianDongJieKou",
          name: "部侧IPv4扫描联动接口-4-142-14",
          meta: { title: "部侧IPv4扫描联动接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧IPv4扫描联动接口/index"),
        },
        {
          path: "IPV4SaoMiaoQiDiaoDuRenWuGuanLi",
          name: "IPv4扫描器调度任务管理-4-142-15",
          meta: { title: "IPv4扫描器调度任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IPv4扫描器调度任务管理/index"),
        },
        {
          path: "IPV6SaoMiaoQiDiaoDuRenWuGuanLi",
          name: "IPv6扫描器调度任务管理-4-142-16",
          meta: { title: "IPv6扫描器调度任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IPv6扫描器调度任务管理/index"),
        },
        {
          path: "DanIPSaoMiaoLiuChengGuanLi",
          name: "单IP扫描流程管理-4-142-17",
          meta: { title: "单IP扫描流程管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/单IP扫描流程管理/index"),
        },
        {
          path: "IPDuanSaoMiaoGuiZeGuanLi",
          name: "IP段扫描规则管理-4-142-18",
          meta: { title: "IP段扫描规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP段扫描规则管理/index"),
        },
        {
          path: "SaoMiaoRenWuDongTaiFenPeiGuiZeGuanLi",
          name: "扫描任务动态分配规则管理-4-142-19",
          meta: { title: "扫描任务动态分配规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描任务动态分配规则管理/index"),
        },
        {
          path: "SaoMiaoCeLüeGuanLi",
          name: "扫描策略管理-4-142-20",
          meta: { title: "扫描策略管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描策略管理/index"),
        },
        {
          path: "SaoMiaoJieGuoShangBaoJieKou",
          name: "扫描结果上报接口-4-142-21",
          meta: { title: "扫描结果上报接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描结果上报接口/index"),
        },
        {
          path: "DingJiDuiXiangShangBaoKuGuanLi",
          name: "定级对象上报库管理-4-142-22",
          meta: { title: "定级对象上报库管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/定级对象上报库管理/index"),
        },
        {
          path: "TeDingZiChanFanWeiMeiJuGuanLi",
          name: "特定资产范围枚举管理-4-142-23",
          meta: { title: "特定资产范围枚举管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/特定资产范围枚举管理/index"),
        },
        {
          path: "BuCeZiChanHuiZongXinXiGuanLi",
          name: "部侧资产汇总信息管理-4-142-24",
          meta: { title: "部侧资产汇总信息管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧资产汇总信息管理/index"),
        },
        {
          path: "ZhongDianWangLuoDanYuanLeiXingZiChanGuanLi",
          name: "重点网络单元类型资产管理-4-142-25",
          meta: { title: "重点网络单元类型资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络单元类型资产管理/index"),
        },
        {
          path: "BianGengZiChanChaXunJieKou",
          name: "变更资产查询接口-4-142-26",
          meta: { title: "变更资产查询接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/变更资产查询接口/index"),
        },
        {
          path: "ZiChanSheBeiPinPaiGuanLi",
          name: "资产设备品牌管理-4-142-27",
          meta: { title: "资产设备品牌管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产设备品牌管理/index"),
        },
        {
          path: "ChuZhiXiaFaGongDanGuanLi",
          name: "处置下发工单管理-4-142-28",
          meta: { title: "处置下发工单管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/处置下发工单管理/index"),
        },
        {
          path: "ZiChanBeiFenGuiZeGuanLi",
          name: "资产备份规则管理-4-142-29",
          meta: { title: "资产备份规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产备份规则管理/index"),
        },
        {
          path: "ZhiLingShangBaoJieKou",
          name: "指令上报接口-4-142-30",
          meta: { title: "指令上报接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/指令上报接口/index"),
        },
        {
          path: "ZiChanFanWeiChaXunJieKou",
          name: "资产范围查询接口-4-142-31",
          meta: { title: "资产范围查询接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产范围查询接口/index"),
        },
        {
          path: "ZiChanZhuangTaiYuJingGuanLi",
          name: "资产状态预警管理-4-142-32",
          meta: { title: "资产状态预警管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产状态预警管理/index"),
        },
        {
          path: "ZiChanBianGengXinXiGuanLi",
          name: "资产变更信息管理-4-142-33",
          meta: { title: "资产变更信息管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产变更信息管理/index"),
        },
        {
          path: "GongXinBuCaiJiCeLüePeiZhiGuanLi",
          name: "工信部采集策略配置管理-4-142-34",
          meta: { title: "工信部采集策略配置管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/工信部采集策略配置管理/index"),
        },
        {
          path: "ZiChanYiLaiChaXunJieKou",
          name: "资产依赖查询接口-4-142-35",
          meta: { title: "资产依赖查询接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产依赖查询接口/index"),
        },
        {
          path: "ZhiLingShangBaoShiXiaoGuanLi",
          name: "指令上报时效管理-4-142-36",
          meta: { title: "指令上报时效管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/指令上报时效管理/index"),
        },
        {
          path: "WuLiZiChanGuanLi",
          name: "物理资产管理-4-142-37",
          meta: { title: "物理资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/物理资产管理/index"),
        },
        {
          path: "SaoMiaoRenWuRiZhiGuanLi",
          name: "扫描任务日志管理-4-142-38",
          meta: { title: "扫描任务日志管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描任务日志管理/index"),
        },
        {
          path: "SaoMiaoRenWuRiZhiShangBaoJieKou",
          name: "扫描任务日志上报接口-4-142-39",
          meta: { title: "扫描任务日志上报接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描任务日志上报接口/index"),
        },
        {
          path: "BuCeSaoMiaoShangBaoShuJuGuanLi",
          name: "部侧扫描上报数据管理-4-142-40",
          meta: { title: "部侧扫描上报数据管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧扫描上报数据管理/index"),
        },
        {
          path: "BuCeJieGuoShangBaoLiuChengGuanLi",
          name: "部侧结果上报流程管理-4-142-41",
          meta: { title: "部侧结果上报流程管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧结果上报流程管理/index"),
        },
        {
          path: "JieGuoShuJuJieXiGuiZeGuanLi",
          name: "结果数据解析规则管理-4-142-42",
          meta: { title: "结果数据解析规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/结果数据解析规则管理/index"),
        },
        {
          path: "SaoMiaoTanZhenGuanLi",
          name: "扫描探针管理-4-142-43",
          meta: { title: "扫描探针管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描探针管理/index"),
        },
        {
          path: "TanZhenShuJuJieXiGuiZeGuanLi",
          name: "探针数据解析规则管理-4-142-44",
          meta: { title: "探针数据解析规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/探针数据解析规则管理/index"),
        },
        {
          path: "CONTENTWenJianShengChengRenWuGuanLi",
          name: "content文件生成任务管理-4-142-45",
          meta: { title: "content文件生成任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/content文件生成任务管理/index"),
        },
        {
          path: "JieGuoWenJianYuLiShiDuiBiGuanLi",
          name: "结果文件与历史对比管理-4-142-46",
          meta: { title: "结果文件与历史对比管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/结果文件与历史对比管理/index"),
        },
        {
          path: "BuCeCONTENTWenJianGuanLi",
          name: "部侧content文件管理-4-142-47",
          meta: { title: "部侧content文件管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧content文件管理/index"),
        },
        {
          path: "WenJianCunChuLuJingGuanLi",
          name: "文件存储路径管理-4-142-48",
          meta: { title: "文件存储路径管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/文件存储路径管理/index"),
        },
        {
          path: "BuCeLiShiShangBaoShuJuFenXi",
          name: "部侧历史上报数据分析-4-142-49",
          meta: { title: "部侧历史上报数据分析" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧历史上报数据分析/index"),
        },
        {
          path: "BuCeShangBaoShiBaiChuZhiLiuChengGuanLi",
          name: "部侧上报失败处置流程管理-4-142-50",
          meta: { title: "部侧上报失败处置流程管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧上报失败处置流程管理/index"),
        },
        {
          path: "ShangBaoShiBaiYuanYinFenXi",
          name: "上报失败原因分析-4-142-51",
          meta: { title: "上报失败原因分析" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/上报失败原因分析/index"),
        },
        {
          path: "WenJianMingMingYuGuiDangGuanLi",
          name: "文件命名与归档管理-4-142-52",
          meta: { title: "文件命名与归档管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/文件命名与归档管理/index"),
        },
        {
          path: "BuCeShangChuanTongDaoGuanLi",
          name: "部侧上传通道管理-4-142-53",
          meta: { title: "部侧上传通道管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧上传通道管理/index"),
        },
        {
          path: "SFTPChuanShuTongDaoJianKong",
          name: "SFTP传输通道监控-4-142-54",
          meta: { title: "SFTP传输通道监控" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/SFTP传输通道监控/index"),
        },
        {
          path: "ShuJuWanZhengXingJiaoYanGuiZeGuanLi",
          name: "数据完整性校验规则管理-4-142-55",
          meta: { title: "数据完整性校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/数据完整性校验规则管理/index"),
        },
        {
          path: "ShangBaoRenWuDiaoDuGuanLi",
          name: "上报任务调度管理-4-142-56",
          meta: { title: "上报任务调度管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/上报任务调度管理/index"),
        },
        {
          path: "ShuJuTongBuGuanLi",
          name: "数据同步管理-4-142-57",
          meta: { title: "数据同步管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/数据同步管理/index"),
        },
        {
          path: "ShangBaoJieGuoJieShouJieKou",
          name: "上报结果接收接口-4-142-58",
          meta: { title: "上报结果接收接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/上报结果接收接口/index"),
        },
        {
          path: "JieShouJieGuoShuJuShenChaGuanLi",
          name: "接收结果数据审查管理-4-142-59",
          meta: { title: "接收结果数据审查管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/接收结果数据审查管理/index"),
        },
        {
          path: "DiaoDuPingTaiChengGongXiaoXiShangChuanJieKou",
          name: "调度平台成功消息上传接口-4-142-60",
          meta: { title: "调度平台成功消息上传接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/调度平台成功消息上传接口/index"),
        },
        {
          path: "GongXinBuNeiWangCaiJiLianDongJieKou",
          name: "工信部内网采集联动接口-4-142-61",
          meta: { title: "工信部内网采集联动接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/工信部内网采集联动接口/index"),
        },
        {
          path: "NeiWangCaiJiRenWuJieShouGuanLi",
          name: "内网采集任务接收管理-4-142-62",
          meta: { title: "内网采集任务接收管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集任务接收管理/index"),
        },
        {
          path: "NeiWangCaiJiRenWuDiaoDuJianKongGuanLi",
          name: "内网采集任务调度监控管理-4-142-63",
          meta: { title: "内网采集任务调度监控管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集任务调度监控管理/index"),
        },
        {
          path: "NeiWangCaiJiZiChanGuanLi",
          name: "内网采集资产管理-4-142-64",
          meta: { title: "内网采集资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集资产管理/index"),
        },
        {
          path: "ZhuJiZiChanBaoBiao",
          name: "主机资产报表-4-142-65",
          meta: { title: "主机资产报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/主机资产报表/index"),
        },
        {
          path: "DengLuCaiJiZhiWenGuanLi",
          name: "登录采集指纹管理-4-142-66",
          meta: { title: "登录采集指纹管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/登录采集指纹管理/index"),
        },
        {
          path: "NeiWangZiChanShiBieMoXingGuanLi",
          name: "内网资产识别模型管理-4-142-67",
          meta: { title: "内网资产识别模型管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网资产识别模型管理/index"),
        },
        {
          path: "ZhuJiZiChanCaiJiGuanLi",
          name: "主机资产采集管理-4-142-68",
          meta: { title: "主机资产采集管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/主机资产采集管理/index"),
        },
        {
          path: "NeiWangCaiJiJieGuoShangBaoJieKou",
          name: "内网采集结果上报接口-4-142-69",
          meta: { title: "内网采集结果上报接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集结果上报接口/index"),
        },
        {
          path: "NeiWangCaiJiZhiLingWenJianGuanLi",
          name: "内网采集指令文件管理-4-142-70",
          meta: { title: "内网采集指令文件管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集指令文件管理/index"),
        },
        {
          path: "NeiWangCaiJiShangBaoShuJuGuanLi",
          name: "内网采集上报数据管理-4-142-71",
          meta: { title: "内网采集上报数据管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集上报数据管理/index"),
        },
        {
          path: "NeiWangZiChanCONTENTJieGuoFanKuiGuanLi",
          name: "内网资产content结果反馈管理-4-142-72",
          meta: { title: "内网资产content结果反馈管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网资产content结果反馈管理/index"),
        },
        {
          path: "CaiJiRenWuRiZhiShangBaoJieKou",
          name: "采集任务日志上报接口-4-142-73",
          meta: { title: "采集任务日志上报接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/采集任务日志上报接口/index"),
        },
        {
          path: "XuNiZiYuanTianBaoGuanLi",
          name: "虚拟资源填报管理-4-142-74",
          meta: { title: "虚拟资源填报管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源填报管理/index"),
        },
        {
          path: "XuNiZiYuanShiYongJianKongGuanLi",
          name: "虚拟资源使用监控管理-4-142-75",
          meta: { title: "虚拟资源使用监控管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源使用监控管理/index"),
        },
        {
          path: "XuNiZiYuanShiYongShenJiGuanLi",
          name: "虚拟资源使用审计管理-4-142-76",
          meta: { title: "虚拟资源使用审计管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源使用审计管理/index"),
        },
        {
          path: "XuNiZiYuanYiChangJianKong",
          name: "虚拟资源异常监控-4-142-77",
          meta: { title: "虚拟资源异常监控" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源异常监控/index"),
        },
        {
          path: "XuNiZiYuanBianGengShenPiLiuChengGuanLi",
          name: "虚拟资源变更审批流程管理-4-142-78",
          meta: { title: "虚拟资源变更审批流程管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源变更审批流程管理/index"),
        },
        {
          path: "XuNiZiYuanPeiEGuanLi",
          name: "虚拟资源配额管理-4-142-79",
          meta: { title: "虚拟资源配额管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源配额管理/index"),
        },
        {
          path: "XuNiZiYuanDiaoDuGuanLi",
          name: "虚拟资源调度管理-4-142-80",
          meta: { title: "虚拟资源调度管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源调度管理/index"),
        },
        {
          path: "GongXinBuZhiChiZuJianGuanLi",
          name: "工信部支持组件管理-4-142-81",
          meta: { title: "工信部支持组件管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/工信部支持组件管理/index"),
        },
        {
          path: "SanFangZiYuanKuGuanLi",
          name: "三方资源库管理-4-142-82",
          meta: { title: "三方资源库管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/三方资源库管理/index"),
        },
        {
          path: "ZuJianKuGuanLi",
          name: "组件库管理-4-142-83",
          meta: { title: "组件库管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/组件库管理/index"),
        },
        {
          path: "IPZiChanZuJianFanKuiJieKou",
          name: "IP资产组件反馈接口-4-142-84",
          meta: { title: "IP资产组件反馈接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP资产组件反馈接口/index"),
        },
        {
          path: "TeDingZiChanZuJianTongBuJieKou",
          name: "特定资产组件同步接口-4-142-85",
          meta: { title: "特定资产组件同步接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/特定资产组件同步接口/index"),
        },
        {
          path: "ZiChanZuJianZhuangTaiChaXunJieKou",
          name: "资产组件状态查询接口-4-142-86",
          meta: { title: "资产组件状态查询接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产组件状态查询接口/index"),
        },
        {
          path: "ZiChanLeiXingGuanLi",
          name: "资产类型管理-4-142-87",
          meta: { title: "资产类型管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产类型管理/index"),
        },
        {
          path: "WangLuoChanPinZiChanGuanLi",
          name: "网络产品资产管理-4-142-88",
          meta: { title: "网络产品资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/网络产品资产管理/index"),
        },
        {
          path: "DianXinSheBeiZiChanGuanLi",
          name: "电信设备资产管理-4-142-89",
          meta: { title: "电信设备资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/电信设备资产管理/index"),
        },
        {
          path: "BanGongWaiSheZiChanGuanLi",
          name: "办公外设资产管理-4-142-90",
          meta: { title: "办公外设资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/办公外设资产管理/index"),
        },
        {
          path: "YingYongRuanJianZiChanGuanLi",
          name: "应用软件资产管理-4-142-91",
          meta: { title: "应用软件资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/应用软件资产管理/index"),
        },
        {
          path: "ZhongDianWangLuoDanYuanLeiXingZhiWenGuanLi",
          name: "重点网络单元类型指纹管理-4-142-92",
          meta: { title: "重点网络单元类型指纹管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络单元类型指纹管理/index"),
        },
        {
          path: "ZhongDianWangLuoSheBeiZhiLingJieShouJieKou",
          name: "重点网络设备指令接收接口-4-142-93",
          meta: { title: "重点网络设备指令接收接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络设备指令接收接口/index"),
        },
        {
          path: "ZhongDianWangLuoSheBeiZhiLingJieXiGuiZeGuanLi",
          name: "重点网络设备指令解析规则管理-4-142-94",
          meta: { title: "重点网络设备指令解析规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络设备指令解析规则管理/index"),
        },
        {
          path: "ZhongDianWangLuoSheBeiJieShouZhiLingFanKuiJieKou",
          name: "重点网络设备接收指令反馈接口-4-142-95",
          meta: { title: "重点网络设备接收指令反馈接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络设备接收指令反馈接口/index"),
        },
        {
          path: "ZhongDianWangLuoSheBeiJieGuoGuanLi",
          name: "重点网络设备结果管理-4-142-96",
          meta: { title: "重点网络设备结果管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络设备结果管理/index"),
        },
        {
          path: "ZhongDianWangLuoSheBeiJieGuoShangBaoJieKou",
          name: "重点网络设备结果上报接口-4-142-97",
          meta: { title: "重点网络设备结果上报接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络设备结果上报接口/index"),
        },
        {
          path: "DaMoXingZiChanGuanLi",
          name: "大模型资产管理-4-142-98",
          meta: { title: "大模型资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/大模型资产管理/index"),
        },
        {
          path: "ChangShangPinPaiXingHaoDaiMaGuanLi",
          name: "厂商品牌型号代码管理-4-142-99",
          meta: { title: "厂商品牌型号代码管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/厂商品牌型号代码管理/index"),
        },
        {
          path: "ZiDongHuaCaiJiFangShiYanZhengGuanLi",
          name: "自动化采集方式验证管理-4-142-100",
          meta: { title: "自动化采集方式验证管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/自动化采集方式验证管理/index"),
        },
        {
          path: "ZiChanFaXianFangShiYiZhiXingJiaoYanGuiZeGuanLi",
          name: "资产发现方式一致性校验规则管理-4-142-101",
          meta: { title: "资产发现方式一致性校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产发现方式一致性校验规则管理/index"),
        },
        {
          path: "CunLiangZiChanDuiBiMoXingGuanLi",
          name: "存量资产对比模型管理-4-142-102",
          meta: { title: "存量资产对比模型管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/存量资产对比模型管理/index"),
        },
        {
          path: "ZiChanFaXianFangShiBianGengShenChaGuanLi",
          name: "资产发现方式变更审查管理-4-142-103",
          meta: { title: "资产发现方式变更审查管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产发现方式变更审查管理/index"),
        },
        {
          path: "ZiDongCaiJiDuiBiBaoBiaoGuanLi",
          name: "自动采集对比报表管理-4-142-104",
          meta: { title: "自动采集对比报表管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/自动采集对比报表管理/index"),
        },
        {
          path: "ZiChanNaGuanTiaoMuFenXiGuanLi",
          name: "资产纳管条目分析管理-4-142-105",
          meta: { title: "资产纳管条目分析管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产纳管条目分析管理/index"),
        },
        {
          path: "ZiChanMingChengJiaoYanGuiZeGuanLi",
          name: "资产名称校验规则管理-4-142-106",
          meta: { title: "资产名称校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产名称校验规则管理/index"),
        },
        {
          path: "ZiChanLeiBieQueShiBaoBiao",
          name: "资产类别缺失报表-4-142-107",
          meta: { title: "资产类别缺失报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产类别缺失报表/index"),
        },
        {
          path: "ZiChanFenLeiJieGouJieXiGuiZeGuanLi",
          name: "资产分类结构解析规则管理-4-142-108",
          meta: { title: "资产分类结构解析规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产分类结构解析规则管理/index"),
        },
        {
          path: "ZiChanLeiBieZiDongHuaJiaoYanRenWuGuanLi",
          name: "资产类别自动化校验任务管理-4-142-109",
          meta: { title: "资产类别自动化校验任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产类别自动化校验任务管理/index"),
        },
        {
          path: "ZiChanIPNaGuanMoNiJiaoYanRenWuGuanLi",
          name: "资产IP纳管模拟校验任务管理-4-142-110",
          meta: { title: "资产IP纳管模拟校验任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产IP纳管模拟校验任务管理/index"),
        },
        {
          path: "NaGuanMoNiJiaoYanGuiZeGuanLi",
          name: "纳管模拟校验规则管理-4-142-111",
          meta: { title: "纳管模拟校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/纳管模拟校验规则管理/index"),
        },
        {
          path: "IPNaGuanDuiBiBaoBiao",
          name: "IP纳管对比报表-4-142-112",
          meta: { title: "IP纳管对比报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP纳管对比报表/index"),
        },
        {
          path: "CunLiangWeiNaGuanZiChanGuanLi",
          name: "存量未纳管资产管理-4-142-113",
          meta: { title: "存量未纳管资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/存量未纳管资产管理/index"),
        },
        {
          path: "XuNiZiChanNaGuanYanZhengGuanLi",
          name: "虚拟资产纳管验证管理-4-142-114",
          meta: { title: "虚拟资产纳管验证管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资产纳管验证管理/index"),
        },
        {
          path: "XuNiZiChanNaGuanDuiBiRenWuGuanLi",
          name: "虚拟资产纳管对比任务管理-4-142-115",
          meta: { title: "虚拟资产纳管对比任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资产纳管对比任务管理/index"),
        },
        {
          path: "XuNiZiChanNaGuanBaoBiao",
          name: "虚拟资产纳管报表-4-142-116",
          meta: { title: "虚拟资产纳管报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资产纳管报表/index"),
        },
        {
          path: "XuNiZiChanWeiNaGuanYuJingGuanLi",
          name: "虚拟资产未纳管预警管理-4-142-117",
          meta: { title: "虚拟资产未纳管预警管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资产未纳管预警管理/index"),
        },
        {
          path: "BaoLouMianZiChanNaGuanGuanLi",
          name: "暴露面资产纳管管理-4-142-118",
          meta: { title: "暴露面资产纳管管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/暴露面资产纳管管理/index"),
        },
        {
          path: "BaoLouMianZiChanNaGuanDuiBiRenWuGuanLi",
          name: "暴露面资产纳管对比任务管理-4-142-119",
          meta: { title: "暴露面资产纳管对比任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/暴露面资产纳管对比任务管理/index"),
        },
        {
          path: "BaoLouMianZiChanNaGuanBaoBiaoBaoBiao",
          name: "暴露面资产纳管报表报表-4-142-120",
          meta: { title: "暴露面资产纳管报表报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/暴露面资产纳管报表报表/index"),
        },
        {
          path: "BaoLouMianZiChanWeiNaGuanYuJingGuanLi",
          name: "暴露面资产未纳管预警管理-4-142-121",
          meta: { title: "暴露面资产未纳管预警管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/暴露面资产未纳管预警管理/index"),
        },
        {
          path: "ZiDingYiXiangYiZhiXingJiaoYanGuanLi",
          name: "自定义项一致性校验管理-4-142-122",
          meta: { title: "自定义项一致性校验管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/自定义项一致性校验管理/index"),
        },
        {
          path: "ZiDingYiXiangJiaoYanJieGuoBaoBiao",
          name: "自定义项校验结果报表-4-142-123",
          meta: { title: "自定义项校验结果报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/自定义项校验结果报表/index"),
        },
        {
          path: "ZiChanXingHaoYiZhiXingJiaoYanRenWuGuanLi",
          name: "资产型号一致性校验任务管理-4-142-124",
          meta: { title: "资产型号一致性校验任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产型号一致性校验任务管理/index"),
        },
        {
          path: "ZiDingYiXiangYiZhiXingJiaoYanGuiZeGuanLi",
          name: "自定义项一致性校验规则管理-4-142-125",
          meta: { title: "自定义项一致性校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/自定义项一致性校验规则管理/index"),
        },
        {
          path: "ZiChanFenLeiXinXiTongBuJieKou",
          name: "资产分类信息同步接口-4-142-126",
          meta: { title: "资产分类信息同步接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产分类信息同步接口/index"),
        },
        {
          path: "IPDuanKouSaoMiaoZhunQueXingJiaoYanRenWuGuanLi",
          name: "IP端口扫描准确性校验任务管理-4-142-127",
          meta: { title: "IP端口扫描准确性校验任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP端口扫描准确性校验任务管理/index"),
        },
        {
          path: "ZiChanGuiShuYuWeiZhiJiaoYanGuiZeGuanLi",
          name: "资产归属与位置校验规则管理-4-142-128",
          meta: { title: "资产归属与位置校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产归属与位置校验规则管理/index"),
        },
        {
          path: "IPKeFangWenXinXiTanCeGuanLi",
          name: "IP可访问信息探测管理-4-142-129",
          meta: { title: "IP可访问信息探测管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP可访问信息探测管理/index"),
        },
        {
          path: "NeiWangCaiJiZiChanMoNiJiaoYanRenWuGuanLi",
          name: "内网采集资产模拟校验任务管理-4-142-130",
          meta: { title: "内网采集资产模拟校验任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集资产模拟校验任务管理/index"),
        },
        {
          path: "CaiJiMoNiJiaoYanGuiZeGuanLi",
          name: "采集模拟校验规则管理-4-142-131",
          meta: { title: "采集模拟校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/采集模拟校验规则管理/index"),
        },
        {
          path: "MoNiCaiJiZiChanBaoBiao",
          name: "模拟采集资产报表-4-142-132",
          meta: { title: "模拟采集资产报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/模拟采集资产报表/index"),
        },
        {
          path: "BeiAnDuiBiJiaoYanGuiZeGuanLi",
          name: "备案对比校验规则管理-4-142-133",
          meta: { title: "备案对比校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/备案对比校验规则管理/index"),
        },
        {
          path: "ZiChanBeiAnRenWuGuanLi",
          name: "资产备案任务管理-4-142-134",
          meta: { title: "资产备案任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产备案任务管理/index"),
        },
        {
          path: "BeiAnYanZhengJieGuoBaoBiao",
          name: "备案验证结果报表-4-142-135",
          meta: { title: "备案验证结果报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/备案验证结果报表/index"),
        },
        {
          path: "ZiChanGuiYiHuaJiaoYanRenWuGuanLi",
          name: "资产归一化校验任务管理-4-142-136",
          meta: { title: "资产归一化校验任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产归一化校验任务管理/index"),
        },
        {
          path: "XiangSiDuTeZhengFenXiGuanLi",
          name: "相似度特征分析管理-4-142-137",
          meta: { title: "相似度特征分析管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/相似度特征分析管理/index"),
        },
        {
          path: "DaiFenXiShuJuGuanLi",
          name: "待分析数据管理-4-142-138",
          meta: { title: "待分析数据管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/待分析数据管理/index"),
        },
        {
          path: "ZiChanXingHaoPiPeiSuanFaGuanLi",
          name: "资产型号匹配算法管理-4-142-139",
          meta: { title: "资产型号匹配算法管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产型号匹配算法管理/index"),
        },
        {
          path: "ZiChanTeZhengFenXiGuiZeGuanLi",
          name: "资产特征分析规则管理-4-142-140",
          meta: { title: "资产特征分析规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产特征分析规则管理/index"),
        },
        {
          path: "ZiChanMiaoShuRongYuShenChaGuanLi",
          name: "资产描述冗余审查管理-4-142-141",
          meta: { title: "资产描述冗余审查管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产描述冗余审查管理/index"),
        },
        {
          path: "BianJieJuLiJiSuanGuanLi",
          name: "边界距离计算管理-4-142-142",
          meta: { title: "边界距离计算管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/边界距离计算管理/index"),
        }
      ],
    },
    ],
    }];

export default examplesRoutes;
