/* Layout */
import Layout from "@/layout";
import Parent from "@/layout/components/ParentView";

const examplesRoutes = [
  {
    path: "/ziChanXinXiShangBaoTiaoZheng",
    name: "资产信息上报调整",
    meta: { title: "资产信息上报调整", icon: "setting" },
    component: Layout,
    children: [
     // ─── JL吉林COSMIC（自动生成）───
    {
      path: "JLJiLinCOSMIC",
      name: "JL吉林COSMIC",
      meta: { title: "JL吉林COSMIC" },
      component: Parent,
      children: [
        {
          path: "IPSaoMiaoZhiLingXiaFaJieKou",
          name: "IP扫描指令下发接口-4-142-1",
          meta: { title: "IP扫描指令下发接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP扫描指令下发接口/index"),
        },
        {
          path: "ZhiLingJieShouRenWuDiaoDuGuanLi",
          name: "指令接收任务调度管理-4-142-2",
          meta: { title: "指令接收任务调度管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/指令接收任务调度管理/index"),
        },
        {
          path: "IPSaoMiaoZhiLingJieShouGuanLi",
          name: "IP扫描指令接收管理-4-142-3",
          meta: { title: "IP扫描指令接收管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP扫描指令接收管理/index"),
        },
        {
          path: "IPSaoMiaoZhiLingFanKuiJieKou",
          name: "IP扫描指令反馈接口-4-142-4",
          meta: { title: "IP扫描指令反馈接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP扫描指令反馈接口/index"),
        },
        {
          path: "SaoMiaoRenWuJieShouGuanLi",
          name: "扫描任务接收管理-4-142-5",
          meta: { title: "扫描任务接收管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描任务接收管理/index"),
        },
        {
          path: "LianDongZhiLingKongZhiGuanLi",
          name: "联动指令控制管理-4-142-6",
          meta: { title: "联动指令控制管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/联动指令控制管理/index"),
        },
        {
          path: "IPSaoMiaoRenWuFenFaLiuChengGuanLi",
          name: "IP扫描任务分发流程管理-4-142-7",
          meta: { title: "IP扫描任务分发流程管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP扫描任务分发流程管理/index"),
        },
        {
          path: "JieShouZhuangTaiFanKuiGuanLi",
          name: "接收状态反馈管理-4-142-8",
          meta: { title: "接收状态反馈管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/接收状态反馈管理/index"),
        },
        {
          path: "ZhiLingFanKuiZhuangTaiTongBuJieKou",
          name: "指令反馈状态同步接口-4-142-9",
          meta: { title: "指令反馈状态同步接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/指令反馈状态同步接口/index"),
        },
        {
          path: "FanKuiZiChanZhuangTaiJianKong",
          name: "反馈资产状态监控-4-142-10",
          meta: { title: "反馈资产状态监控" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/反馈资产状态监控/index"),
        },
        {
          path: "ZhiLingFanKuiChaoShiYuJingGuanLi",
          name: "指令反馈超时预警管理-4-142-11",
          meta: { title: "指令反馈超时预警管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/指令反馈超时预警管理/index"),
        },
        {
          path: "FanKuiZiChanWanZhengXingJiaoYanGuanLi",
          name: "反馈资产完整性校验管理-4-142-12",
          meta: { title: "反馈资产完整性校验管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/反馈资产完整性校验管理/index"),
        },
        {
          path: "GongXinBuLianDongSaoMiaoRenWuGuanLi",
          name: "工信部联动扫描任务管理-4-142-13",
          meta: { title: "工信部联动扫描任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/工信部联动扫描任务管理/index"),
        },
        {
          path: "BuCeIPV4SaoMiaoLianDongJieKou",
          name: "部侧IPv4扫描联动接口-4-142-14",
          meta: { title: "部侧IPv4扫描联动接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧IPv4扫描联动接口/index"),
        },
        {
          path: "IPV4SaoMiaoQiDiaoDuRenWuGuanLi",
          name: "IPv4扫描器调度任务管理-4-142-15",
          meta: { title: "IPv4扫描器调度任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IPv4扫描器调度任务管理/index"),
        },
        {
          path: "IPV6SaoMiaoQiDiaoDuRenWuGuanLi",
          name: "IPv6扫描器调度任务管理-4-142-16",
          meta: { title: "IPv6扫描器调度任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IPv6扫描器调度任务管理/index"),
        },
        {
          path: "DanIPSaoMiaoLiuChengGuanLi",
          name: "单IP扫描流程管理-4-142-17",
          meta: { title: "单IP扫描流程管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/单IP扫描流程管理/index"),
        },
        {
          path: "IPDuanSaoMiaoGuiZeGuanLi",
          name: "IP段扫描规则管理-4-142-18",
          meta: { title: "IP段扫描规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP段扫描规则管理/index"),
        },
        {
          path: "SaoMiaoRenWuDongTaiFenPeiGuiZeGuanLi",
          name: "扫描任务动态分配规则管理-4-142-19",
          meta: { title: "扫描任务动态分配规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描任务动态分配规则管理/index"),
        },
        {
          path: "SaoMiaoCeLüeGuanLi",
          name: "扫描策略管理-4-142-20",
          meta: { title: "扫描策略管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描策略管理/index"),
        },
        {
          path: "SaoMiaoJieGuoShangBaoJieKou",
          name: "扫描结果上报接口-4-142-21",
          meta: { title: "扫描结果上报接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描结果上报接口/index"),
        },
        {
          path: "DingJiDuiXiangShangBaoKuGuanLi",
          name: "定级对象上报库管理-4-142-22",
          meta: { title: "定级对象上报库管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/定级对象上报库管理/index"),
        },
        {
          path: "TeDingZiChanFanWeiMeiJuGuanLi",
          name: "特定资产范围枚举管理-4-142-23",
          meta: { title: "特定资产范围枚举管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/特定资产范围枚举管理/index"),
        },
        {
          path: "BuCeZiChanHuiZongXinXiGuanLi",
          name: "部侧资产汇总信息管理-4-142-24",
          meta: { title: "部侧资产汇总信息管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧资产汇总信息管理/index"),
        },
        {
          path: "ZhongDianWangLuoDanYuanLeiXingZiChanGuanLi",
          name: "重点网络单元类型资产管理-4-142-25",
          meta: { title: "重点网络单元类型资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络单元类型资产管理/index"),
        },
        {
          path: "BianGengZiChanChaXunJieKou",
          name: "变更资产查询接口-4-142-26",
          meta: { title: "变更资产查询接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/变更资产查询接口/index"),
        },
        {
          path: "ZiChanSheBeiPinPaiGuanLi",
          name: "资产设备品牌管理-4-142-27",
          meta: { title: "资产设备品牌管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产设备品牌管理/index"),
        },
        {
          path: "ChuZhiXiaFaGongDanGuanLi",
          name: "处置下发工单管理-4-142-28",
          meta: { title: "处置下发工单管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/处置下发工单管理/index"),
        },
        {
          path: "ZiChanBeiFenGuiZeGuanLi",
          name: "资产备份规则管理-4-142-29",
          meta: { title: "资产备份规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产备份规则管理/index"),
        },
        {
          path: "ZhiLingShangBaoJieKou",
          name: "指令上报接口-4-142-30",
          meta: { title: "指令上报接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/指令上报接口/index"),
        },
        {
          path: "ZiChanFanWeiChaXunJieKou",
          name: "资产范围查询接口-4-142-31",
          meta: { title: "资产范围查询接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产范围查询接口/index"),
        },
        {
          path: "ZiChanZhuangTaiYuJingGuanLi",
          name: "资产状态预警管理-4-142-32",
          meta: { title: "资产状态预警管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产状态预警管理/index"),
        },
        {
          path: "ZiChanBianGengXinXiGuanLi",
          name: "资产变更信息管理-4-142-33",
          meta: { title: "资产变更信息管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产变更信息管理/index"),
        },
        {
          path: "GongXinBuCaiJiCeLüePeiZhiGuanLi",
          name: "工信部采集策略配置管理-4-142-34",
          meta: { title: "工信部采集策略配置管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/工信部采集策略配置管理/index"),
        },
        {
          path: "ZiChanYiLaiChaXunJieKou",
          name: "资产依赖查询接口-4-142-35",
          meta: { title: "资产依赖查询接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产依赖查询接口/index"),
        },
        {
          path: "ZhiLingShangBaoShiXiaoGuanLi",
          name: "指令上报时效管理-4-142-36",
          meta: { title: "指令上报时效管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/指令上报时效管理/index"),
        },
        {
          path: "WuLiZiChanGuanLi",
          name: "物理资产管理-4-142-37",
          meta: { title: "物理资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/物理资产管理/index"),
        },
        {
          path: "SaoMiaoRenWuRiZhiGuanLi",
          name: "扫描任务日志管理-4-142-38",
          meta: { title: "扫描任务日志管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描任务日志管理/index"),
        },
        {
          path: "SaoMiaoRenWuRiZhiShangBaoJieKou",
          name: "扫描任务日志上报接口-4-142-39",
          meta: { title: "扫描任务日志上报接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描任务日志上报接口/index"),
        },
        {
          path: "BuCeSaoMiaoShangBaoShuJuGuanLi",
          name: "部侧扫描上报数据管理-4-142-40",
          meta: { title: "部侧扫描上报数据管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧扫描上报数据管理/index"),
        },
        {
          path: "BuCeJieGuoShangBaoLiuChengGuanLi",
          name: "部侧结果上报流程管理-4-142-41",
          meta: { title: "部侧结果上报流程管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧结果上报流程管理/index"),
        },
        {
          path: "JieGuoShuJuJieXiGuiZeGuanLi",
          name: "结果数据解析规则管理-4-142-42",
          meta: { title: "结果数据解析规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/结果数据解析规则管理/index"),
        },
        {
          path: "SaoMiaoTanZhenGuanLi",
          name: "扫描探针管理-4-142-43",
          meta: { title: "扫描探针管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/扫描探针管理/index"),
        },
        {
          path: "TanZhenShuJuJieXiGuiZeGuanLi",
          name: "探针数据解析规则管理-4-142-44",
          meta: { title: "探针数据解析规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/探针数据解析规则管理/index"),
        },
        {
          path: "CONTENTWenJianShengChengRenWuGuanLi",
          name: "content文件生成任务管理-4-142-45",
          meta: { title: "content文件生成任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/content文件生成任务管理/index"),
        },
        {
          path: "JieGuoWenJianYuLiShiDuiBiGuanLi",
          name: "结果文件与历史对比管理-4-142-46",
          meta: { title: "结果文件与历史对比管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/结果文件与历史对比管理/index"),
        },
        {
          path: "BuCeCONTENTWenJianGuanLi",
          name: "部侧content文件管理-4-142-47",
          meta: { title: "部侧content文件管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧content文件管理/index"),
        },
        {
          path: "WenJianCunChuLuJingGuanLi",
          name: "文件存储路径管理-4-142-48",
          meta: { title: "文件存储路径管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/文件存储路径管理/index"),
        },
        {
          path: "BuCeLiShiShangBaoShuJuFenXi",
          name: "部侧历史上报数据分析-4-142-49",
          meta: { title: "部侧历史上报数据分析" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧历史上报数据分析/index"),
        },
        {
          path: "BuCeShangBaoShiBaiChuZhiLiuChengGuanLi",
          name: "部侧上报失败处置流程管理-4-142-50",
          meta: { title: "部侧上报失败处置流程管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧上报失败处置流程管理/index"),
        },
        {
          path: "ShangBaoShiBaiYuanYinFenXi",
          name: "上报失败原因分析-4-142-51",
          meta: { title: "上报失败原因分析" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/上报失败原因分析/index"),
        },
        {
          path: "WenJianMingMingYuGuiDangGuanLi",
          name: "文件命名与归档管理-4-142-52",
          meta: { title: "文件命名与归档管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/文件命名与归档管理/index"),
        },
        {
          path: "BuCeShangChuanTongDaoGuanLi",
          name: "部侧上传通道管理-4-142-53",
          meta: { title: "部侧上传通道管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/部侧上传通道管理/index"),
        },
        {
          path: "SFTPChuanShuTongDaoJianKong",
          name: "SFTP传输通道监控-4-142-54",
          meta: { title: "SFTP传输通道监控" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/SFTP传输通道监控/index"),
        },
        {
          path: "ShuJuWanZhengXingJiaoYanGuiZeGuanLi",
          name: "数据完整性校验规则管理-4-142-55",
          meta: { title: "数据完整性校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/数据完整性校验规则管理/index"),
        },
        {
          path: "ShangBaoRenWuDiaoDuGuanLi",
          name: "上报任务调度管理-4-142-56",
          meta: { title: "上报任务调度管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/上报任务调度管理/index"),
        },
        {
          path: "ShuJuTongBuGuanLi",
          name: "数据同步管理-4-142-57",
          meta: { title: "数据同步管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/数据同步管理/index"),
        },
        {
          path: "ShangBaoJieGuoJieShouJieKou",
          name: "上报结果接收接口-4-142-58",
          meta: { title: "上报结果接收接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/上报结果接收接口/index"),
        },
        {
          path: "JieShouJieGuoShuJuShenChaGuanLi",
          name: "接收结果数据审查管理-4-142-59",
          meta: { title: "接收结果数据审查管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/接收结果数据审查管理/index"),
        },
        {
          path: "DiaoDuPingTaiChengGongXiaoXiShangChuanJieKou",
          name: "调度平台成功消息上传接口-4-142-60",
          meta: { title: "调度平台成功消息上传接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/调度平台成功消息上传接口/index"),
        },
        {
          path: "GongXinBuNeiWangCaiJiLianDongJieKou",
          name: "工信部内网采集联动接口-4-142-61",
          meta: { title: "工信部内网采集联动接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/工信部内网采集联动接口/index"),
        },
        {
          path: "NeiWangCaiJiRenWuJieShouGuanLi",
          name: "内网采集任务接收管理-4-142-62",
          meta: { title: "内网采集任务接收管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集任务接收管理/index"),
        },
        {
          path: "NeiWangCaiJiRenWuDiaoDuJianKongGuanLi",
          name: "内网采集任务调度监控管理-4-142-63",
          meta: { title: "内网采集任务调度监控管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集任务调度监控管理/index"),
        },
        {
          path: "NeiWangCaiJiZiChanGuanLi",
          name: "内网采集资产管理-4-142-64",
          meta: { title: "内网采集资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集资产管理/index"),
        },
        {
          path: "ZhuJiZiChanBaoBiao",
          name: "主机资产报表-4-142-65",
          meta: { title: "主机资产报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/主机资产报表/index"),
        },
        {
          path: "DengLuCaiJiZhiWenGuanLi",
          name: "登录采集指纹管理-4-142-66",
          meta: { title: "登录采集指纹管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/登录采集指纹管理/index"),
        },
        {
          path: "NeiWangZiChanShiBieMoXingGuanLi",
          name: "内网资产识别模型管理-4-142-67",
          meta: { title: "内网资产识别模型管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网资产识别模型管理/index"),
        },
        {
          path: "ZhuJiZiChanCaiJiGuanLi",
          name: "主机资产采集管理-4-142-68",
          meta: { title: "主机资产采集管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/主机资产采集管理/index"),
        },
        {
          path: "NeiWangCaiJiJieGuoShangBaoJieKou",
          name: "内网采集结果上报接口-4-142-69",
          meta: { title: "内网采集结果上报接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集结果上报接口/index"),
        },
        {
          path: "NeiWangCaiJiZhiLingWenJianGuanLi",
          name: "内网采集指令文件管理-4-142-70",
          meta: { title: "内网采集指令文件管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集指令文件管理/index"),
        },
        {
          path: "NeiWangCaiJiShangBaoShuJuGuanLi",
          name: "内网采集上报数据管理-4-142-71",
          meta: { title: "内网采集上报数据管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集上报数据管理/index"),
        },
        {
          path: "NeiWangZiChanCONTENTJieGuoFanKuiGuanLi",
          name: "内网资产content结果反馈管理-4-142-72",
          meta: { title: "内网资产content结果反馈管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网资产content结果反馈管理/index"),
        },
        {
          path: "CaiJiRenWuRiZhiShangBaoJieKou",
          name: "采集任务日志上报接口-4-142-73",
          meta: { title: "采集任务日志上报接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/采集任务日志上报接口/index"),
        },
        {
          path: "XuNiZiYuanTianBaoGuanLi",
          name: "虚拟资源填报管理-4-142-74",
          meta: { title: "虚拟资源填报管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源填报管理/index"),
        },
        {
          path: "XuNiZiYuanShiYongJianKongGuanLi",
          name: "虚拟资源使用监控管理-4-142-75",
          meta: { title: "虚拟资源使用监控管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源使用监控管理/index"),
        },
        {
          path: "XuNiZiYuanShiYongShenJiGuanLi",
          name: "虚拟资源使用审计管理-4-142-76",
          meta: { title: "虚拟资源使用审计管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源使用审计管理/index"),
        },
        {
          path: "XuNiZiYuanYiChangJianKong",
          name: "虚拟资源异常监控-4-142-77",
          meta: { title: "虚拟资源异常监控" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源异常监控/index"),
        },
        {
          path: "XuNiZiYuanBianGengShenPiLiuChengGuanLi",
          name: "虚拟资源变更审批流程管理-4-142-78",
          meta: { title: "虚拟资源变更审批流程管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源变更审批流程管理/index"),
        },
        {
          path: "XuNiZiYuanPeiEGuanLi",
          name: "虚拟资源配额管理-4-142-79",
          meta: { title: "虚拟资源配额管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源配额管理/index"),
        },
        {
          path: "XuNiZiYuanDiaoDuGuanLi",
          name: "虚拟资源调度管理-4-142-80",
          meta: { title: "虚拟资源调度管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资源调度管理/index"),
        },
        {
          path: "GongXinBuZhiChiZuJianGuanLi",
          name: "工信部支持组件管理-4-142-81",
          meta: { title: "工信部支持组件管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/工信部支持组件管理/index"),
        },
        {
          path: "SanFangZiYuanKuGuanLi",
          name: "三方资源库管理-4-142-82",
          meta: { title: "三方资源库管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/三方资源库管理/index"),
        },
        {
          path: "ZuJianKuGuanLi",
          name: "组件库管理-4-142-83",
          meta: { title: "组件库管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/组件库管理/index"),
        },
        {
          path: "IPZiChanZuJianFanKuiJieKou",
          name: "IP资产组件反馈接口-4-142-84",
          meta: { title: "IP资产组件反馈接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP资产组件反馈接口/index"),
        },
        {
          path: "TeDingZiChanZuJianTongBuJieKou",
          name: "特定资产组件同步接口-4-142-85",
          meta: { title: "特定资产组件同步接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/特定资产组件同步接口/index"),
        },
        {
          path: "ZiChanZuJianZhuangTaiChaXunJieKou",
          name: "资产组件状态查询接口-4-142-86",
          meta: { title: "资产组件状态查询接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产组件状态查询接口/index"),
        },
        {
          path: "ZiChanLeiXingGuanLi",
          name: "资产类型管理-4-142-87",
          meta: { title: "资产类型管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产类型管理/index"),
        },
        {
          path: "WangLuoChanPinZiChanGuanLi",
          name: "网络产品资产管理-4-142-88",
          meta: { title: "网络产品资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/网络产品资产管理/index"),
        },
        {
          path: "DianXinSheBeiZiChanGuanLi",
          name: "电信设备资产管理-4-142-89",
          meta: { title: "电信设备资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/电信设备资产管理/index"),
        },
        {
          path: "BanGongWaiSheZiChanGuanLi",
          name: "办公外设资产管理-4-142-90",
          meta: { title: "办公外设资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/办公外设资产管理/index"),
        },
        {
          path: "YingYongRuanJianZiChanGuanLi",
          name: "应用软件资产管理-4-142-91",
          meta: { title: "应用软件资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/应用软件资产管理/index"),
        },
        {
          path: "ZhongDianWangLuoDanYuanLeiXingZhiWenGuanLi",
          name: "重点网络单元类型指纹管理-4-142-92",
          meta: { title: "重点网络单元类型指纹管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络单元类型指纹管理/index"),
        },
        {
          path: "ZhongDianWangLuoSheBeiZhiLingJieShouJieKou",
          name: "重点网络设备指令接收接口-4-142-93",
          meta: { title: "重点网络设备指令接收接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络设备指令接收接口/index"),
        },
        {
          path: "ZhongDianWangLuoSheBeiZhiLingJieXiGuiZeGuanLi",
          name: "重点网络设备指令解析规则管理-4-142-94",
          meta: { title: "重点网络设备指令解析规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络设备指令解析规则管理/index"),
        },
        {
          path: "ZhongDianWangLuoSheBeiJieShouZhiLingFanKuiJieKou",
          name: "重点网络设备接收指令反馈接口-4-142-95",
          meta: { title: "重点网络设备接收指令反馈接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络设备接收指令反馈接口/index"),
        },
        {
          path: "ZhongDianWangLuoSheBeiJieGuoGuanLi",
          name: "重点网络设备结果管理-4-142-96",
          meta: { title: "重点网络设备结果管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络设备结果管理/index"),
        },
        {
          path: "ZhongDianWangLuoSheBeiJieGuoShangBaoJieKou",
          name: "重点网络设备结果上报接口-4-142-97",
          meta: { title: "重点网络设备结果上报接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/重点网络设备结果上报接口/index"),
        },
        {
          path: "DaMoXingZiChanGuanLi",
          name: "大模型资产管理-4-142-98",
          meta: { title: "大模型资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/大模型资产管理/index"),
        },
        {
          path: "ChangShangPinPaiXingHaoDaiMaGuanLi",
          name: "厂商品牌型号代码管理-4-142-99",
          meta: { title: "厂商品牌型号代码管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/厂商品牌型号代码管理/index"),
        },
        {
          path: "ZiDongHuaCaiJiFangShiYanZhengGuanLi",
          name: "自动化采集方式验证管理-4-142-100",
          meta: { title: "自动化采集方式验证管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/自动化采集方式验证管理/index"),
        },
        {
          path: "ZiChanFaXianFangShiYiZhiXingJiaoYanGuiZeGuanLi",
          name: "资产发现方式一致性校验规则管理-4-142-101",
          meta: { title: "资产发现方式一致性校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产发现方式一致性校验规则管理/index"),
        },
        {
          path: "CunLiangZiChanDuiBiMoXingGuanLi",
          name: "存量资产对比模型管理-4-142-102",
          meta: { title: "存量资产对比模型管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/存量资产对比模型管理/index"),
        },
        {
          path: "ZiChanFaXianFangShiBianGengShenChaGuanLi",
          name: "资产发现方式变更审查管理-4-142-103",
          meta: { title: "资产发现方式变更审查管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产发现方式变更审查管理/index"),
        },
        {
          path: "ZiDongCaiJiDuiBiBaoBiaoGuanLi",
          name: "自动采集对比报表管理-4-142-104",
          meta: { title: "自动采集对比报表管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/自动采集对比报表管理/index"),
        },
        {
          path: "ZiChanNaGuanTiaoMuFenXiGuanLi",
          name: "资产纳管条目分析管理-4-142-105",
          meta: { title: "资产纳管条目分析管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产纳管条目分析管理/index"),
        },
        {
          path: "ZiChanMingChengJiaoYanGuiZeGuanLi",
          name: "资产名称校验规则管理-4-142-106",
          meta: { title: "资产名称校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产名称校验规则管理/index"),
        },
        {
          path: "ZiChanLeiBieQueShiBaoBiao",
          name: "资产类别缺失报表-4-142-107",
          meta: { title: "资产类别缺失报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产类别缺失报表/index"),
        },
        {
          path: "ZiChanFenLeiJieGouJieXiGuiZeGuanLi",
          name: "资产分类结构解析规则管理-4-142-108",
          meta: { title: "资产分类结构解析规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产分类结构解析规则管理/index"),
        },
        {
          path: "ZiChanLeiBieZiDongHuaJiaoYanRenWuGuanLi",
          name: "资产类别自动化校验任务管理-4-142-109",
          meta: { title: "资产类别自动化校验任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产类别自动化校验任务管理/index"),
        },
        {
          path: "ZiChanIPNaGuanMoNiJiaoYanRenWuGuanLi",
          name: "资产IP纳管模拟校验任务管理-4-142-110",
          meta: { title: "资产IP纳管模拟校验任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产IP纳管模拟校验任务管理/index"),
        },
        {
          path: "NaGuanMoNiJiaoYanGuiZeGuanLi",
          name: "纳管模拟校验规则管理-4-142-111",
          meta: { title: "纳管模拟校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/纳管模拟校验规则管理/index"),
        },
        {
          path: "IPNaGuanDuiBiBaoBiao",
          name: "IP纳管对比报表-4-142-112",
          meta: { title: "IP纳管对比报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP纳管对比报表/index"),
        },
        {
          path: "CunLiangWeiNaGuanZiChanGuanLi",
          name: "存量未纳管资产管理-4-142-113",
          meta: { title: "存量未纳管资产管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/存量未纳管资产管理/index"),
        },
        {
          path: "XuNiZiChanNaGuanYanZhengGuanLi",
          name: "虚拟资产纳管验证管理-4-142-114",
          meta: { title: "虚拟资产纳管验证管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资产纳管验证管理/index"),
        },
        {
          path: "XuNiZiChanNaGuanDuiBiRenWuGuanLi",
          name: "虚拟资产纳管对比任务管理-4-142-115",
          meta: { title: "虚拟资产纳管对比任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资产纳管对比任务管理/index"),
        },
        {
          path: "XuNiZiChanNaGuanBaoBiao",
          name: "虚拟资产纳管报表-4-142-116",
          meta: { title: "虚拟资产纳管报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资产纳管报表/index"),
        },
        {
          path: "XuNiZiChanWeiNaGuanYuJingGuanLi",
          name: "虚拟资产未纳管预警管理-4-142-117",
          meta: { title: "虚拟资产未纳管预警管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/虚拟资产未纳管预警管理/index"),
        },
        {
          path: "BaoLouMianZiChanNaGuanGuanLi",
          name: "暴露面资产纳管管理-4-142-118",
          meta: { title: "暴露面资产纳管管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/暴露面资产纳管管理/index"),
        },
        {
          path: "BaoLouMianZiChanNaGuanDuiBiRenWuGuanLi",
          name: "暴露面资产纳管对比任务管理-4-142-119",
          meta: { title: "暴露面资产纳管对比任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/暴露面资产纳管对比任务管理/index"),
        },
        {
          path: "BaoLouMianZiChanNaGuanBaoBiaoBaoBiao",
          name: "暴露面资产纳管报表报表-4-142-120",
          meta: { title: "暴露面资产纳管报表报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/暴露面资产纳管报表报表/index"),
        },
        {
          path: "BaoLouMianZiChanWeiNaGuanYuJingGuanLi",
          name: "暴露面资产未纳管预警管理-4-142-121",
          meta: { title: "暴露面资产未纳管预警管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/暴露面资产未纳管预警管理/index"),
        },
        {
          path: "ZiDingYiXiangYiZhiXingJiaoYanGuanLi",
          name: "自定义项一致性校验管理-4-142-122",
          meta: { title: "自定义项一致性校验管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/自定义项一致性校验管理/index"),
        },
        {
          path: "ZiDingYiXiangJiaoYanJieGuoBaoBiao",
          name: "自定义项校验结果报表-4-142-123",
          meta: { title: "自定义项校验结果报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/自定义项校验结果报表/index"),
        },
        {
          path: "ZiChanXingHaoYiZhiXingJiaoYanRenWuGuanLi",
          name: "资产型号一致性校验任务管理-4-142-124",
          meta: { title: "资产型号一致性校验任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产型号一致性校验任务管理/index"),
        },
        {
          path: "ZiDingYiXiangYiZhiXingJiaoYanGuiZeGuanLi",
          name: "自定义项一致性校验规则管理-4-142-125",
          meta: { title: "自定义项一致性校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/自定义项一致性校验规则管理/index"),
        },
        {
          path: "ZiChanFenLeiXinXiTongBuJieKou",
          name: "资产分类信息同步接口-4-142-126",
          meta: { title: "资产分类信息同步接口" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产分类信息同步接口/index"),
        },
        {
          path: "IPDuanKouSaoMiaoZhunQueXingJiaoYanRenWuGuanLi",
          name: "IP端口扫描准确性校验任务管理-4-142-127",
          meta: { title: "IP端口扫描准确性校验任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP端口扫描准确性校验任务管理/index"),
        },
        {
          path: "ZiChanGuiShuYuWeiZhiJiaoYanGuiZeGuanLi",
          name: "资产归属与位置校验规则管理-4-142-128",
          meta: { title: "资产归属与位置校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产归属与位置校验规则管理/index"),
        },
        {
          path: "IPKeFangWenXinXiTanCeGuanLi",
          name: "IP可访问信息探测管理-4-142-129",
          meta: { title: "IP可访问信息探测管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/IP可访问信息探测管理/index"),
        },
        {
          path: "NeiWangCaiJiZiChanMoNiJiaoYanRenWuGuanLi",
          name: "内网采集资产模拟校验任务管理-4-142-130",
          meta: { title: "内网采集资产模拟校验任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/内网采集资产模拟校验任务管理/index"),
        },
        {
          path: "CaiJiMoNiJiaoYanGuiZeGuanLi",
          name: "采集模拟校验规则管理-4-142-131",
          meta: { title: "采集模拟校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/采集模拟校验规则管理/index"),
        },
        {
          path: "MoNiCaiJiZiChanBaoBiao",
          name: "模拟采集资产报表-4-142-132",
          meta: { title: "模拟采集资产报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/模拟采集资产报表/index"),
        },
        {
          path: "BeiAnDuiBiJiaoYanGuiZeGuanLi",
          name: "备案对比校验规则管理-4-142-133",
          meta: { title: "备案对比校验规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/备案对比校验规则管理/index"),
        },
        {
          path: "ZiChanBeiAnRenWuGuanLi",
          name: "资产备案任务管理-4-142-134",
          meta: { title: "资产备案任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产备案任务管理/index"),
        },
        {
          path: "BeiAnYanZhengJieGuoBaoBiao",
          name: "备案验证结果报表-4-142-135",
          meta: { title: "备案验证结果报表" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/备案验证结果报表/index"),
        },
        {
          path: "ZiChanGuiYiHuaJiaoYanRenWuGuanLi",
          name: "资产归一化校验任务管理-4-142-136",
          meta: { title: "资产归一化校验任务管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产归一化校验任务管理/index"),
        },
        {
          path: "XiangSiDuTeZhengFenXiGuanLi",
          name: "相似度特征分析管理-4-142-137",
          meta: { title: "相似度特征分析管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/相似度特征分析管理/index"),
        },
        {
          path: "DaiFenXiShuJuGuanLi",
          name: "待分析数据管理-4-142-138",
          meta: { title: "待分析数据管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/待分析数据管理/index"),
        },
        {
          path: "ZiChanXingHaoPiPeiSuanFaGuanLi",
          name: "资产型号匹配算法管理-4-142-139",
          meta: { title: "资产型号匹配算法管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产型号匹配算法管理/index"),
        },
        {
          path: "ZiChanTeZhengFenXiGuiZeGuanLi",
          name: "资产特征分析规则管理-4-142-140",
          meta: { title: "资产特征分析规则管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产特征分析规则管理/index"),
        },
        {
          path: "ZiChanMiaoShuRongYuShenChaGuanLi",
          name: "资产描述冗余审查管理-4-142-141",
          meta: { title: "资产描述冗余审查管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/资产描述冗余审查管理/index"),
        },
        {
          path: "BianJieJuLiJiSuanGuanLi",
          name: "边界距离计算管理-4-142-142",
          meta: { title: "边界距离计算管理" },
          component: () => import("@/views/资产信息上报调整/JL吉林COSMIC/边界距离计算管理/index"),
        }
      ],
    },
    // --- YN云南COSMIC（自动生成）---
    {
      path: "YNYunNanCOSMIC",
      name: "YN云南COSMIC",
      meta: { title: "YN云南COSMIC" },
      component: () => import("@/layout/components/ParentView"),
      children: [
{
          path: "GongXinBuZhiLingXinXiXiaFaJieKou",
          name: "工信部指令信息下发接口-4-216-1",
          meta: { title: "工信部指令信息下发接口" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部指令信息下发接口/index"),
        },
{
          path: "ZhiLingXinXiZiDuanGuanLi",
          name: "指令信息字段管理-4-216-2",
          meta: { title: "指令信息字段管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/指令信息字段管理/index"),
        },
{
          path: "ZhiLingXinXiZiDuanBianGengShenPiLiuChengGuanLi",
          name: "指令信息字段变更审批流程管理-4-216-3",
          meta: { title: "指令信息字段变更审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/指令信息字段变更审批流程管理/index"),
        },
{
          path: "ZhiLingXiaFaJieKouGuanLi",
          name: "指令下发接口管理-4-216-4",
          component: Parent,
          meta: { title: "指令下发接口管理" },
          children: [
            { path: "", name: "指令下发接口管理-4-216-4-main", meta: { title: "指令下发接口管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/指令下发接口管理/index") },
            { path: "ZhiLingXiaFaSheZhiXinXiGuanLi", name: "指令下发接口管理-4-216-4-sub1", meta: { title: "指令下发设置信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/指令下发接口管理/指令下发设置信息管理/index") },
            { path: "ZhiLingXiaFaJieKouCuoWuShiJianGuanLi", name: "指令下发接口管理-4-216-4-sub2", meta: { title: "指令下发接口错误事件管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/指令下发接口管理/指令下发接口错误事件管理/index") },
            { path: "ZhiLingXiaFaJieKouFangCuanGaiXinXiGuanLi", name: "指令下发接口管理-4-216-4-sub3", meta: { title: "指令下发接口防篡改信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/指令下发接口管理/指令下发接口防篡改信息管理/index") },
            { path: "GongXinBuZhiLingXinXiGuanLi", name: "指令下发接口管理-4-216-4-sub4", meta: { title: "工信部指令信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/指令下发接口管理/工信部指令信息管理/index") },
          ]
        },
{
          path: "ZhiLingXiaFaJieKouCuoWuXinXiGuanLi",
          name: "指令下发接口错误信息管理-4-216-4-sub3",
          meta: { title: "指令下发接口错误信息管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/指令下发接口错误信息管理/index"),
        },
{
          path: "ZiChanZhuangTaiCaiJiGuanLi",
          name: "资产状态采集管理-4-216-5",
          meta: { title: "资产状态采集管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产状态采集管理/index"),
        },
{
          path: "ZiChanZhuangTaiCaiJiJieGuoShenHeLiuChengGuanLi",
          name: "资产状态采集结果审核流程管理-4-216-6",
          meta: { title: "资产状态采集结果审核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产状态采集结果审核流程管理/index"),
        },
{
          path: "GongXinBuZiChanZhuangTaiGuanLi",
          name: "工信部资产状态管理-4-216-7",
          meta: { title: "工信部资产状态管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产状态管理/index"),
        },
{
          path: "ZiChanJianBiaoGuanLi",
          name: "资产简表管理-4-216-8",
          meta: { title: "资产简表管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产简表管理/index"),
        },
{
          path: "ChaXunGongXinBuZhiLingXinXiXiangQing",
          name: "查询工信部指令信息详情-4-216-9",
          meta: { title: "查询工信部指令信息详情" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/查询工信部指令信息详情/index"),
        },
{
          path: "GongXinBuChaXunZhiLingShenPiLiuChengGuanLi",
          name: "工信部查询指令审批流程管理-4-216-10",
          meta: { title: "工信部查询指令审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部查询指令审批流程管理/index"),
        },
{
          path: "GongXinBuShangBaoIPGuanLi",
          name: "工信部上报IP管理-4-216-11",
          meta: { title: "工信部上报IP管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部上报IP管理/index"),
        },
{
          path: "GongXinBuShangBaoIPShuJuShenPiLiuChengGuanLi",
          name: "工信部上报IP数据审批流程管理-4-216-12",
          meta: { title: "工信部上报IP数据审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部上报IP数据审批流程管理/index"),
        },
{
          path: "GongXinBuGuanLiZhiLingXiaFaJieKouGuanLi",
          name: "工信部管理指令下发接口管理-4-216-13",
          meta: { title: "工信部管理指令下发接口管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部管理指令下发接口管理/index"),
        },
{
          path: "GongXinBuZiChanBiaoQianGuanLi",
          name: "工信部资产标签管理-4-216-14",
          meta: { title: "工信部资产标签管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产标签管理/index"),
        },
{
          path: "GongDanChuZhiZhiLingGuanLi",
          name: "工单处置指令管理-4-216-15",
          meta: { title: "工单处置指令管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工单处置指令管理/index"),
        },
{
          path: "GongDanChuZhiShenPiLiuChengGuanLi",
          name: "工单处置审批流程管理-4-216-16",
          meta: { title: "工单处置审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工单处置审批流程管理/index"),
        },
{
          path: "GongXinBuWangLuoDanYuanGuanLi",
          name: "工信部网络单元管理-4-216-17",
          meta: { title: "工信部网络单元管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部网络单元管理/index"),
        },
{
          path: "ZiChanXinXiJieGuoFanKuiJieKou",
          name: "资产信息结果反馈接口-4-216-18",
          meta: { title: "资产信息结果反馈接口" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产信息结果反馈接口/index"),
        },
{
          path: "GongXinBuDingJiBeiAnShuJuGuanLi",
          name: "工信部定级备案数据管理-4-216-19",
          meta: { title: "工信部定级备案数据管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部定级备案数据管理/index"),
        },
{
          path: "FanKuiJieGuoShuJuShangBaoGuanLi",
          name: "反馈结果数据上报管理-4-216-20",
          meta: { title: "反馈结果数据上报管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/反馈结果数据上报管理/index"),
        },
{
          path: "GongXinBuShuJuShangBaoLiuChengGuanLi",
          name: "工信部数据上报流程管理-4-216-21",
          meta: { title: "工信部数据上报流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部数据上报流程管理/index"),
        },
{
          path: "GongXinBuZiChanJianBiaoFanKuiGuanLi",
          name: "工信部资产简表反馈管理-4-216-22",
          meta: { title: "工信部资产简表反馈管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产简表反馈管理/index"),
        },
{
          path: "DingJiDuiXiangZiChanChaXunJieKouGuanLi",
          name: "定级对象资产查询接口管理-4-216-23",
          meta: { title: "定级对象资产查询接口管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/定级对象资产查询接口管理/index"),
        },
{
          path: "DingJiDuiXiangZiChanShenPiLiuChengGuanLi",
          name: "定级对象资产审批流程管理-4-216-24",
          meta: { title: "定级对象资产审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/定级对象资产审批流程管理/index"),
        },
{
          path: "DingJiDuiXiangChaXunJieKouXiuGai",
          name: "定级对象查询接口修改-4-216-25",
          meta: { title: "定级对象查询接口修改" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/定级对象查询接口修改/index"),
        },
{
          path: "IPDiZhiZiChanGuanLi",
          name: "IP地址资产管理-4-216-26",
          meta: { title: "IP地址资产管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/IP地址资产管理/index"),
        },
{
          path: "IPDiZhiZiChanShangBaoLiuChengGuanLi",
          name: "IP地址资产上报流程管理-4-216-27",
          meta: { title: "IP地址资产上报流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/IP地址资产上报流程管理/index"),
        },
{
          path: "IPDiZhiZiChanChaXunJieKouGuanLi",
          name: "IP地址资产查询接口管理-4-216-28",
          meta: { title: "IP地址资产查询接口管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/IP地址资产查询接口管理/index"),
        },
{
          path: "IPDiZhiBianGengGongDanGuanLi",
          name: "IP地址变更工单管理-4-216-29",
          meta: { title: "IP地址变更工单管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/IP地址变更工单管理/index"),
        },
{
          path: "TeDingZiChanFanWeiGuanLi",
          name: "特定资产范围管理-4-216-30",
          meta: { title: "特定资产范围管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/特定资产范围管理/index"),
        },
{
          path: "TeDingZiChanFanWeiGongDanBianGengGuanLi",
          name: "特定资产范围工单变更管理-4-216-31",
          meta: { title: "特定资产范围工单变更管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/特定资产范围工单变更管理/index"),
        },
{
          path: "DuanNeiZiChanChaXunJieKouGuanLi",
          name: "段内资产查询接口管理-4-216-32",
          meta: { title: "段内资产查询接口管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/段内资产查询接口管理/index"),
        },
{
          path: "ZhongDianWangLuoDanYuanZiChanLeiXingGuanLi",
          name: "重点网络单元资产类型管理-4-216-33",
          meta: { title: "重点网络单元资产类型管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/重点网络单元资产类型管理/index"),
        },
{
          path: "ZiChanBianGengChaXunJieKouGuanLi",
          name: "资产变更查询接口管理-4-216-34",
          meta: { title: "资产变更查询接口管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产变更查询接口管理/index"),
        },
{
          path: "ZiChanBuLuChaXunJieKouGuanLi",
          name: "资产补录查询接口管理-4-216-35",
          meta: { title: "资产补录查询接口管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产补录查询接口管理/index"),
        },
{
          path: "GongXinBuZiChanBuLuLiuChengGuanLi",
          name: "工信部资产补录流程管理-4-216-36",
          meta: { title: "工信部资产补录流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产补录流程管理/index"),
        },
{
          path: "ZiChanBianGengGuanLi",
          name: "资产变更管理-4-216-37",
          meta: { title: "资产变更管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产变更管理/index"),
        },
{
          path: "ZiChanBianGengLiuChengGuanLi",
          name: "资产变更流程管理-4-216-38",
          meta: { title: "资产变更流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产变更流程管理/index"),
        },
{
          path: "ZiChanBeiFenGuanLi",
          name: "资产备份管理-4-216-39",
          meta: { title: "资产备份管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产备份管理/index"),
        },
{
          path: "XiaFaZhiLingGaoJingGuanLi",
          name: "下发指令告警管理-4-216-40",
          meta: { title: "下发指令告警管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/下发指令告警管理/index"),
        },
{
          path: "XiaFaZhiLingCeLüeXinXiGuanLi",
          name: "下发指令策略信息管理-4-216-41",
          meta: { title: "下发指令策略信息管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/下发指令策略信息管理/index"),
        },
{
          path: "XiaFaZhiLingCeLüeShenPiLiuChengGuanLi",
          name: "下发指令策略审批流程管理-4-216-42",
          meta: { title: "下发指令策略审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/下发指令策略审批流程管理/index"),
        },
{
          path: "XiaFaZhiLingZiDongXiangYingGuanLi",
          name: "下发指令自动响应管理-4-216-43",
          meta: { title: "下发指令自动响应管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/下发指令自动响应管理/index"),
        },
{
          path: "XiaFaZhiLingGaoJingYiChangXingWeiGuanLi",
          name: "下发指令告警异常行为管理-4-216-44",
          meta: { title: "下发指令告警异常行为管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/下发指令告警异常行为管理/index"),
        },
{
          path: "XiaFaZhiLingYiChangGaoJingChuZhiGongDanGuanLi",
          name: "下发指令异常告警处置工单管理-4-216-45",
          meta: { title: "下发指令异常告警处置工单管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/下发指令异常告警处置工单管理/index"),
        },
{
          path: "XiaFaZhiLingWeiXieQingBaoGuanLi",
          name: "下发指令威胁情报管理-4-216-46",
          meta: { title: "下发指令威胁情报管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/下发指令威胁情报管理/index"),
        },
{
          path: "ZiChanZhuangTaiXiaFaJieKou",
          name: "资产状态下发接口-4-216-47",
          meta: { title: "资产状态下发接口" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产状态下发接口/index"),
        },
{
          path: "GongXinBuZiChanSIGNGuanLi",
          name: "工信部资产sign管理-4-216-48",
          meta: { title: "工信部资产sign管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产sign管理/index"),
        },
{
          path: "GongXinBuZiChanQingDanGuanLi",
          name: "工信部资产清单管理-4-216-49",
          meta: { title: "工信部资产清单管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产清单管理/index"),
        },
{
          path: "GongXinBuZiChanQingDanShenPiLiuChengGuanLi",
          name: "工信部资产清单审批流程管理-4-216-50",
          meta: { title: "工信部资产清单审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产清单审批流程管理/index"),
        },
{
          path: "ZiChanXinXiShangBaoJieKou",
          name: "资产信息上报接口-4-216-51",
          meta: { title: "资产信息上报接口" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产信息上报接口/index"),
        },
{
          path: "ZiChanXinXiShangBaoRenWuGuanLi",
          name: "资产信息上报任务管理-4-216-52",
          meta: { title: "资产信息上报任务管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产信息上报任务管理/index"),
        },
{
          path: "ZiChanXinXiShangBaoRenWuShenPiLiuChengGuanLi",
          name: "资产信息上报任务审批流程管理-4-216-53",
          meta: { title: "资产信息上报任务审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产信息上报任务审批流程管理/index"),
        },
{
          path: "GongXinBuZiChanBianHaoGenZongGuanLi",
          name: "工信部资产编号跟踪管理-4-216-54",
          meta: { title: "工信部资产编号跟踪管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产编号跟踪管理/index"),
        },
{
          path: "ZiChanShangBaoXinXiGengXinJieKou",
          name: "资产上报信息更新接口-4-216-55",
          meta: { title: "资产上报信息更新接口" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产上报信息更新接口/index"),
        },
{
          path: "GongXinBuZiChanShuXingGuanLi",
          name: "工信部资产属性管理-4-216-56",
          meta: { title: "工信部资产属性管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产属性管理/index"),
        },
{
          path: "GongXinBuZiChanHeGuiGuanLi",
          name: "工信部资产合规管理-4-216-57",
          meta: { title: "工信部资产合规管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产合规管理/index"),
        },
{
          path: "GongXinBuZiChanHeGuiShenPiLiuChengGuanLi",
          name: "工信部资产合规审批流程管理-4-216-58",
          meta: { title: "工信部资产合规审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产合规审批流程管理/index"),
        },
{
          path: "ZiChanIPShangBaoJieKou",
          name: "资产IP上报接口-4-216-59",
          meta: { title: "资产IP上报接口" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产IP上报接口/index"),
        },
{
          path: "ZiChanShangBaoIPGaoJingGuanLi",
          name: "资产上报IP告警管理-4-216-60",
          meta: { title: "资产上报IP告警管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产上报IP告警管理/index"),
        },
{
          path: "ASSETIPGuanLi",
          name: "AssetIP管理-4-216-61",
          meta: { title: "AssetIP管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/AssetIP管理/index"),
        },
{
          path: "ZiChanBiaoQianPeiZhiGuanLi",
          name: "资产标签配置管理-4-216-62",
          meta: { title: "资产标签配置管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产标签配置管理/index"),
        },
{
          path: "ZiChanShangBaoBiaoQianYiChangGaoJingGuanLi",
          name: "资产上报标签异常告警管理-4-216-63",
          meta: { title: "资产上报标签异常告警管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产上报标签异常告警管理/index"),
        },
{
          path: "ZiChanShangBaoBiaoQianYiChangXiaoChuShenPiLiuChengGuanLi",
          name: "资产上报标签异常消除审批流程管理-4-216-64",
          meta: { title: "资产上报标签异常消除审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产上报标签异常消除审批流程管理/index"),
        },
{
          path: "ZiChanBiaoQianGengXinJieKou",
          name: "资产标签更新接口-4-216-65",
          meta: { title: "资产标签更新接口" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产标签更新接口/index"),
        },
{
          path: "GongXinBuASSETNMGaoJingGuanLi",
          name: "工信部AssetNM告警管理-4-216-66",
          meta: { title: "工信部AssetNM告警管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部AssetNM告警管理/index"),
        },
{
          path: "XiTongMingChengGengXinJieKou",
          name: "系统名称更新接口-4-216-67",
          meta: { title: "系统名称更新接口" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/系统名称更新接口/index"),
        },
{
          path: "WangLuoDanYuanPeiZhiGuanLi",
          name: "网络单元配置管理-4-216-68",
          meta: { title: "网络单元配置管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/网络单元配置管理/index"),
        },
{
          path: "ZiChanShangBaoWangLuoDanYuanLeiXingYiChangGaoJingGuanLi",
          name: "资产上报网络单元类型异常告警管理-4-216-69",
          meta: { title: "资产上报网络单元类型异常告警管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产上报网络单元类型异常告警管理/index"),
        },
{
          path: "ZiChanFaXianFangShiPeiZhiGuanLi",
          name: "资产发现方式配置管理-4-216-70",
          meta: { title: "资产发现方式配置管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产发现方式配置管理/index"),
        },
{
          path: "ZiChanShangBaoWuLiWeiZhiJiHeGuanLi",
          name: "资产上报物理位置稽核管理-4-216-71",
          meta: { title: "资产上报物理位置稽核管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产上报物理位置稽核管理/index"),
        },
{
          path: "ZiChanWuLiWeiZhiJiHeGongDanGuanLi",
          name: "资产物理位置稽核工单管理-4-216-72",
          meta: { title: "资产物理位置稽核工单管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产物理位置稽核工单管理/index"),
        },
{
          path: "ZiChanShangBaoBeiAnGuanLi",
          name: "资产上报备案管理-4-216-73",
          meta: { title: "资产上报备案管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产上报备案管理/index"),
        },
{
          path: "GongXinBuBeiAnJiHeGuanLi",
          name: "工信部备案稽核管理-4-216-74",
          meta: { title: "工信部备案稽核管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部备案稽核管理/index"),
        },
{
          path: "GongXinBuZiChanJiHeLiuChengGuanLi",
          name: "工信部资产稽核流程管理-4-216-75",
          meta: { title: "工信部资产稽核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产稽核流程管理/index"),
        },
{
          path: "GongXinBuZiChanShangBaoXinXiTuiSongJieKou",
          name: "工信部资产上报信息推送接口-4-216-76",
          meta: { title: "工信部资产上报信息推送接口" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产上报信息推送接口/index"),
        },
{
          path: "ZiDongHuaCaiJiLüXinXiGuanLi",
          name: "自动化采集率信息管理-4-216-77",
          meta: { title: "自动化采集率信息管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/自动化采集率信息管理/index"),
        },
{
          path: "ZiDongCaiJiLüDuiBiRenWuGuanLi",
          name: "自动采集率对比任务管理-4-216-78",
          meta: { title: "自动采集率对比任务管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/自动采集率对比任务管理/index"),
        },
{
          path: "ZiDongHuaCaiJiLüChuZhiGongDanGuanLi",
          name: "自动化采集率处置工单管理-4-216-79",
          meta: { title: "自动化采集率处置工单管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/自动化采集率处置工单管理/index"),
        },
{
          path: "ZiDongCaiJiLüJianKongGuanLi",
          name: "自动采集率监控管理-4-216-80",
          meta: { title: "自动采集率监控管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/自动采集率监控管理/index"),
        },
{
          path: "ZiDongCaiJiLüJiHe",
          name: "自动采集率稽核-4-216-81",
          meta: { title: "自动采集率稽核" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/自动采集率稽核/index"),
        },
{
          path: "ZiDongHuaCaiJiLüJiHeLiuChengGuanLi",
          name: "自动化采集率稽核流程管理-4-216-82",
          meta: { title: "自动化采集率稽核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/自动化采集率稽核流程管理/index"),
        },
{
          path: "ZiDongHuaCaiJiLüSuanFaGuanLi",
          name: "自动化采集率算法管理-4-216-83",
          meta: { title: "自动化采集率算法管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/自动化采集率算法管理/index"),
        },
{
          path: "ZiDongHuaCaiJiLüBaoBiaoGuanLi",
          name: "自动化采集率报表管理-4-216-84",
          meta: { title: "自动化采集率报表管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/自动化采集率报表管理/index"),
        },
{
          path: "ZiDongHuaCaiJiLüTuiSongJieKou",
          name: "自动化采集率推送接口-4-216-85",
          meta: { title: "自动化采集率推送接口" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/自动化采集率推送接口/index"),
        },
{
          path: "GongXinBuZiChanCaiJiGuanLi",
          name: "工信部资产采集管理-4-216-86",
          meta: { title: "工信部资产采集管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产采集管理/index"),
        },
{
          path: "GongXinBuCaiJiLüGuanLi",
          name: "工信部采集率管理-4-216-87",
          meta: { title: "工信部采集率管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部采集率管理/index"),
        },
{
          path: "GongXinBuCaiJiLüShiBieRenWuGuanLi",
          name: "工信部采集率识别任务管理-4-216-88",
          meta: { title: "工信部采集率识别任务管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部采集率识别任务管理/index"),
        },
{
          path: "GongXinBuCaiJiLüLunXunRenWuGuanLi",
          name: "工信部采集率轮巡任务管理-4-216-89",
          meta: { title: "工信部采集率轮巡任务管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部采集率轮巡任务管理/index"),
        },
{
          path: "GongXinBuCaiJiLüShiShiXingJianKongGuanLi",
          name: "工信部采集率实时性监控管理-4-216-90",
          meta: { title: "工信部采集率实时性监控管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部采集率实时性监控管理/index"),
        },
{
          path: "CaiJiLüYiZhiXingGuanLi",
          name: "采集率一致性管理-4-216-91",
          meta: { title: "采集率一致性管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/采集率一致性管理/index"),
        },
{
          path: "GongXinBuZiChanCaiJiZhiLiangGuanLi",
          name: "工信部资产采集质量管理-4-216-92",
          meta: { title: "工信部资产采集质量管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产采集质量管理/index"),
        },
{
          path: "GongXinBuCaiJiLüYiChangJianCeGuanLi",
          name: "工信部采集率异常检测管理-4-216-93",
          meta: { title: "工信部采集率异常检测管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部采集率异常检测管理/index"),
        },
{
          path: "GongXinBuCaiJiChuZhiGongDanGuanLi",
          name: "工信部采集处置工单管理-4-216-94",
          meta: { title: "工信部采集处置工单管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部采集处置工单管理/index"),
        },
{
          path: "ZiDongHuaCaiJiLüShuJuGanZhiYuChaXun",
          name: "自动化采集率数据感知与查询-4-216-95",
          meta: { title: "自动化采集率数据感知与查询" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/自动化采集率数据感知与查询/index"),
        },
{
          path: "ZiChanIPKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "资产IP考核准确性指标管理-4-216-96",
          meta: { title: "资产IP考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产IP考核准确性指标管理/index"),
        },
{
          path: "IPLeiXingKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "IP类型考核准确性指标管理-4-216-97",
          meta: { title: "IP类型考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/IP类型考核准确性指标管理/index"),
        },
{
          path: "QiTaIPKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "其他IP考核准确性指标管理-4-216-98",
          meta: { title: "其他IP考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/其他IP考核准确性指标管理/index"),
        },
{
          path: "ZiChanXinXiKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "资产信息考核准确性指标管理-4-216-99",
          meta: { title: "资产信息考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产信息考核准确性指标管理/index"),
        },
{
          path: "ZiChanDengJiKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "资产等级考核准确性指标管理-4-216-100",
          meta: { title: "资产等级考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产等级考核准确性指标管理/index"),
        },
{
          path: "GuanLiXianTiaoKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "管理线条考核准确性指标管理-4-216-101",
          meta: { title: "管理线条考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/管理线条考核准确性指标管理/index"),
        },
{
          path: "ZiChanShengFenKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "资产省份考核准确性指标管理-4-216-102",
          meta: { title: "资产省份考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产省份考核准确性指标管理/index"),
        },
{
          path: "ZiChanLeiXingKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "资产类型考核准确性指标管理-4-216-103",
          meta: { title: "资产类型考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产类型考核准确性指标管理/index"),
        },
{
          path: "SheBeiChangShangKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "设备厂商考核准确性指标管理-4-216-104",
          meta: { title: "设备厂商考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/设备厂商考核准确性指标管理/index"),
        },
{
          path: "SheBeiPinPaiKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "设备品牌考核准确性指标管理-4-216-105",
          meta: { title: "设备品牌考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/设备品牌考核准确性指标管理/index"),
        },
{
          path: "CPUChangShangKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "CPU厂商考核准确性指标管理-4-216-106",
          meta: { title: "CPU厂商考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/CPU厂商考核准确性指标管理/index"),
        },
{
          path: "NeiCunChangShangKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "内存厂商考核准确性指标管理-4-216-107",
          meta: { title: "内存厂商考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/内存厂商考核准确性指标管理/index"),
        },
{
          path: "JiaoHuanXinPianChangShangKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "交换芯片厂商考核准确性指标管理-4-216-108",
          meta: { title: "交换芯片厂商考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/交换芯片厂商考核准确性指标管理/index"),
        },
{
          path: "ZiChanQiTaZhiBiaoKaoHeZhunQueXingJiHeGuanLi",
          name: "资产其他指标考核准确性稽核管理-4-216-109",
          meta: { title: "资产其他指标考核准确性稽核管理" },
          component: Parent,
          children: [
            { path: "", redirect: "index" },
            { path: "index", name: "资产其他指标考核准确性稽核管理-4-216-109-main", meta: { title: "资产其他指标考核准确性稽核管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核准确性稽核管理/index") },
            { path: "KaiYuanKuangJiaZiDianXinXiGuanLi", name: "资产其他指标考核准确性稽核管理-4-216-109-sub1", meta: { title: "开源框架数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核准确性稽核管理/开源框架数据字典信息管理/index") },
            { path: "KaiYuanKuangJiaShangChuanRenWuGuanLi", name: "资产其他指标考核准确性稽核管理-4-216-109-sub2", meta: { title: "开源框架考核上传任务管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核准确性稽核管理/开源框架考核上传任务管理/index") },
            { path: "ChanPinJieMianYuYanZiDianXinXiGuanLi", name: "资产其他指标考核准确性稽核管理-4-216-109-sub3", meta: { title: "产品界面语言数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核准确性稽核管理/产品界面语言数据字典信息管理/index") },
            { path: "CaoZuoXiTongLeiXingZiDianXinXiGuanLi", name: "资产其他指标考核准确性稽核管理-4-216-109-sub4", meta: { title: "操作系统类型数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核准确性稽核管理/操作系统类型数据字典信息管理/index") },
            { path: "YingJianHuanJingZiDianXinXiGuanLi", name: "资产其他指标考核准确性稽核管理-4-216-109-sub5", meta: { title: "硬件环境数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核准确性稽核管理/硬件环境数据字典信息管理/index") },
            { path: "RuanJianHuanJingZiDianXinXiGuanLi", name: "资产其他指标考核准确性稽核管理-4-216-109-sub6", meta: { title: "软件环境数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核准确性稽核管理/软件环境数据字典信息管理/index") },
            { path: "WangLuoDanYuanLeiXingZiDianXinXiGuanLi", name: "资产其他指标考核准确性稽核管理-4-216-109-sub7", meta: { title: "网络单元类型数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核准确性稽核管理/网络单元类型数据字典信息管理/index") },
            { path: "DingJiDuiXiangMingChengZiDianXinXiGuanLi", name: "资产其他指标考核准确性稽核管理-4-216-109-sub8", meta: { title: "定级对象名称数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核准确性稽核管理/定级对象名称数据字典信息管理/index") },
            { path: "DingJiDuiXiangMingChengShangChuanRenWuGuanLi", name: "资产其他指标考核准确性稽核管理-4-216-109-sub9", meta: { title: "定级对象名称考核上传任务管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核准确性稽核管理/定级对象名称考核上传任务管理/index") },
            { path: "SuoShuAnQuanYuZiDianXinXiGuanLi", name: "资产其他指标考核准确性稽核管理-4-216-109-sub10", meta: { title: "所属安全域数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核准确性稽核管理/所属安全域数据字典信息管理/index") },
            { path: "SuoShuAnQuanYuShangChuanRenWuGuanLi", name: "资产其他指标考核准确性稽核管理-4-216-109-sub11", meta: { title: "所属安全域考核上传任务管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核准确性稽核管理/所属安全域考核上传任务管理/index") },
          ],
        },
{
          path: "GongXinBuShangBaoShuJuZhunQueXingShenPiLiuChengGuanLi",
          name: "工信部上报数据准确性审批流程管理-4-216-110",
          meta: { title: "工信部上报数据准确性审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部上报数据准确性审批流程管理/index"),
        },
{
          path: "ShangBaoShuJuZhunQueXingShenHeGongDanGuanLi",
          name: "上报数据准确性审核工单管理-4-216-111",
          meta: { title: "上报数据准确性审核工单管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/上报数据准确性审核工单管理/index"),
        },
{
          path: "ShangBaoShuJuKaoHeZhunQueXingZhiBiaoGuanLi",
          name: "上报数据考核准确性指标管理-4-216-112",
          meta: { title: "上报数据考核准确性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/上报数据考核准确性指标管理/index"),
        },
{
          path: "GongXinBuZhunQueHuaXiuGaiNengLiGongJu",
          name: "工信部准确化修改能力工具-4-216-113",
          meta: { title: "工信部准确化修改能力工具" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部准确化修改能力工具/index"),
        },
{
          path: "ZiChanIPKaoHeXiangMuWanZhengXingZhiBiaoGuanLi",
          name: "资产IP考核项目完整性指标管理-4-216-114",
          meta: { title: "资产IP考核项目完整性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产IP考核项目完整性指标管理/index"),
        },
{
          path: "IPLeiXingKaoHeXiangMuWanZhengXingZhiBiaoGuanLi",
          name: "IP类型考核项目完整性指标管理-4-216-115",
          meta: { title: "IP类型考核项目完整性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/IP类型考核项目完整性指标管理/index"),
        },
{
          path: "ZiChanMingChengKaoHeXiangMuWanZhengXingZhiBiaoGuanLi",
          name: "资产名称考核项目完整性指标管理-4-216-116",
          meta: { title: "资产名称考核项目完整性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产名称考核项目完整性指标管理/index"),
        },
{
          path: "ZiChanDengJiKaoHeXiangMuWanZhengXingZhiBiaoGuanLi",
          name: "资产等级考核项目完整性指标管理-4-216-117",
          meta: { title: "资产等级考核项目完整性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产等级考核项目完整性指标管理/index"),
        },
{
          path: "GuanLiXianTiaoKaoHeXiangMuWanZhengXingZhiBiaoGuanLi",
          name: "管理线条考核项目完整性指标管理-4-216-118",
          meta: { title: "管理线条考核项目完整性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/管理线条考核项目完整性指标管理/index"),
        },
{
          path: "ZiChanShengFenKaoHeXiangMuWanZhengXingZhiBiaoGuanLi",
          name: "资产省份考核项目完整性指标管理-4-216-119",
          meta: { title: "资产省份考核项目完整性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产省份考核项目完整性指标管理/index"),
        },
{
          path: "ZiChanLeiXingKaoHeXiangMuWanZhengXingZhiBiaoGuanLi",
          name: "资产类型考核项目完整性指标管理-4-216-120",
          meta: { title: "资产类型考核项目完整性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产类型考核项目完整性指标管理/index"),
        },
{
          path: "SheBeiChangShangKaoHeXiangMuWanZhengXingZhiBiaoGuanLi",
          name: "设备厂商考核项目完整性指标管理-4-216-121",
          meta: { title: "设备厂商考核项目完整性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/设备厂商考核项目完整性指标管理/index"),
        },
{
          path: "SheBeiPinPaiKaoHeXiangMuWanZhengXingZhiBiaoGuanLi",
          name: "设备品牌考核项目完整性指标管理-4-216-122",
          meta: { title: "设备品牌考核项目完整性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/设备品牌考核项目完整性指标管理/index"),
        },
{
          path: "CPUChangShangKaoHeXiangMuWanZhengXingZhiBiaoGuanLi",
          name: "CPU厂商考核项目完整性指标管理-4-216-123",
          meta: { title: "CPU厂商考核项目完整性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/CPU厂商考核项目完整性指标管理/index"),
        },
{
          path: "NeiCunChangShangKaoHeXiangMuWanZhengXingZhiBiaoGuanLi",
          name: "内存厂商考核项目完整性指标管理-4-216-124",
          meta: { title: "内存厂商考核项目完整性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/内存厂商考核项目完整性指标管理/index"),
        },
{
          path: "JiaoHuanXinPianChangShangKaoHeXiangMuWanZhengXingZhiBiaoGuanLi",
          name: "交换芯片厂商考核项目完整性指标管理-4-216-125",
          meta: { title: "交换芯片厂商考核项目完整性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/交换芯片厂商考核项目完整性指标管理/index"),
        },
{
          path: "ZiChanQiTaZhiBiaoKaoHeXiangMuWanZhengXingJiHeGuanLi",
          name: "资产其他指标考核项目完整性稽核管理-4-216-126",
          meta: { title: "资产其他指标考核项目完整性稽核管理" },
          component: Parent,
          children: [
            { path: "", redirect: "index" },
            { path: "index", name: "资产其他指标考核项目完整性稽核管理-4-216-126-main", meta: { title: "资产其他指标考核项目完整性稽核管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核项目完整性稽核管理/index") },
            { path: "KaiYuanKuangJiaZiDianXinXiGuanLi", name: "资产其他指标考核项目完整性稽核管理-4-216-126-sub1", meta: { title: "开源框架数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核项目完整性稽核管理/开源框架数据字典信息管理/index") },
            { path: "KaiYuanKuangJiaShangChuanRenWuGuanLi", name: "资产其他指标考核项目完整性稽核管理-4-216-126-sub2", meta: { title: "开源框架考核上传任务管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核项目完整性稽核管理/开源框架考核上传任务管理/index") },
            { path: "ChanPinJieMianYuYanZiDianXinXiGuanLi", name: "资产其他指标考核项目完整性稽核管理-4-216-126-sub3", meta: { title: "产品界面语言数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核项目完整性稽核管理/产品界面语言数据字典信息管理/index") },
            { path: "CaoZuoXiTongLeiXingZiDianXinXiGuanLi", name: "资产其他指标考核项目完整性稽核管理-4-216-126-sub4", meta: { title: "操作系统类型数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核项目完整性稽核管理/操作系统类型数据字典信息管理/index") },
            { path: "YingJianHuanJingZiDianXinXiGuanLi", name: "资产其他指标考核项目完整性稽核管理-4-216-126-sub5", meta: { title: "硬件环境数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核项目完整性稽核管理/硬件环境数据字典信息管理/index") },
            { path: "RuanJianHuanJingZiDianXinXiGuanLi", name: "资产其他指标考核项目完整性稽核管理-4-216-126-sub6", meta: { title: "软件环境数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核项目完整性稽核管理/软件环境数据字典信息管理/index") },
            { path: "WangLuoDanYuanLeiXingZiDianXinXiGuanLi", name: "资产其他指标考核项目完整性稽核管理-4-216-126-sub7", meta: { title: "网络单元类型数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核项目完整性稽核管理/网络单元类型数据字典信息管理/index") },
            { path: "DingJiDuiXiangMingChengZiDianXinXiGuanLi", name: "资产其他指标考核项目完整性稽核管理-4-216-126-sub8", meta: { title: "定级对象名称数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核项目完整性稽核管理/定级对象名称数据字典信息管理/index") },
            { path: "DingJiDuiXiangMingChengShangChuanRenWuGuanLi", name: "资产其他指标考核项目完整性稽核管理-4-216-126-sub9", meta: { title: "定级对象名称考核上传任务管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核项目完整性稽核管理/定级对象名称考核上传任务管理/index") },
            { path: "SuoShuAnQuanYuZiDianXinXiGuanLi", name: "资产其他指标考核项目完整性稽核管理-4-216-126-sub10", meta: { title: "所属安全域数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核项目完整性稽核管理/所属安全域数据字典信息管理/index") },
            { path: "SuoShuAnQuanYuShangChuanRenWuGuanLi", name: "资产其他指标考核项目完整性稽核管理-4-216-126-sub11", meta: { title: "所属安全域考核上传任务管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核项目完整性稽核管理/所属安全域考核上传任务管理/index") },
          ],
        },
{
          path: "ShangBaoShuJuKaoHeXiangMuWanZhengXingZhiBiaoGuanLi",
          name: "上报数据考核项目完整性指标管理-4-216-127",
          meta: { title: "上报数据考核项目完整性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/上报数据考核项目完整性指标管理/index"),
        },
{
          path: "ShangBaoShuJuWanZhengXingShenHeGongDanGuanLi",
          name: "上报数据完整性审核工单管理-4-216-128",
          meta: { title: "上报数据完整性审核工单管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/上报数据完整性审核工单管理/index"),
        },
{
          path: "GongXinBuWanZhengHuaXiuGaiNengLiGongJu",
          name: "工信部完整化修改能力工具-4-216-129",
          meta: { title: "工信部完整化修改能力工具" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部完整化修改能力工具/index"),
        },
{
          path: "GongXinBuShangBaoShuJuWanZhengXingShenPiLiuChengGuanLi",
          name: "工信部上报数据完整性审批流程管理-4-216-130",
          meta: { title: "工信部上报数据完整性审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部上报数据完整性审批流程管理/index"),
        },
{
          path: "ZiChanIPKaoHeZhiLiangKeYongXingZhiBiaoGuanLi",
          name: "资产IP考核质量可用性指标管理-4-216-131",
          meta: { title: "资产IP考核质量可用性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产IP考核质量可用性指标管理/index"),
        },
{
          path: "IPLeiXingKaoHeZhiLiangKeYongXingZhiBiaoGuanLi",
          name: "IP类型考核质量可用性指标管理-4-216-132",
          meta: { title: "IP类型考核质量可用性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/IP类型考核质量可用性指标管理/index"),
        },
{
          path: "ZiChanMingChengKaoHeZhiLiangKeYongXingZhiBiaoGuanLi",
          name: "资产名称考核质量可用性指标管理-4-216-133",
          meta: { title: "资产名称考核质量可用性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产名称考核质量可用性指标管理/index"),
        },
{
          path: "GuanLiXianTiaoKaoHeZhiLiangKeYongXingZhiBiaoGuanLi",
          name: "管理线条考核质量可用性指标管理-4-216-134",
          meta: { title: "管理线条考核质量可用性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/管理线条考核质量可用性指标管理/index"),
        },
{
          path: "ZiChanShengFenKaoHeZhiLiangKeYongXingZhiBiaoGuanLi",
          name: "资产省份考核质量可用性指标管理-4-216-135",
          meta: { title: "资产省份考核质量可用性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产省份考核质量可用性指标管理/index"),
        },
{
          path: "ZiChanLeiXingKaoHeZhiLiangKeYongXingZhiBiaoGuanLi",
          name: "资产类型考核质量可用性指标管理-4-216-136",
          meta: { title: "资产类型考核质量可用性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产类型考核质量可用性指标管理/index"),
        },
{
          path: "SheBeiChangShangKaoHeZhiLiangKeYongXingZhiBiaoGuanLi",
          name: "设备厂商考核质量可用性指标管理-4-216-137",
          meta: { title: "设备厂商考核质量可用性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/设备厂商考核质量可用性指标管理/index"),
        },
{
          path: "CPUChangShangKaoHeZhiLiangKeYongXingZhiBiaoGuanLi",
          name: "CPU厂商考核质量可用性指标管理-4-216-138",
          meta: { title: "CPU厂商考核质量可用性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/CPU厂商考核质量可用性指标管理/index"),
        },
{
          path: "NeiCunChangShangKaoHeZhiLiangKeYongXingZhiBiaoGuanLi",
          name: "内存厂商考核质量可用性指标管理-4-216-139",
          meta: { title: "内存厂商考核质量可用性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/内存厂商考核质量可用性指标管理/index"),
        },
{
          path: "JiaoHuanXinPianChangShangKaoHeZhiLiangKeYongXingZhiBiaoGuanLi",
          name: "交换芯片厂商考核质量可用性指标管理-4-216-140",
          meta: { title: "交换芯片厂商考核质量可用性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/交换芯片厂商考核质量可用性指标管理/index"),
        },
{
          path: "ZiChanQiTaZhiBiaoKaoHeZhiLiangKeYongXingJiHeGuanLi",
          name: "资产其他指标考核质量可用性稽核管理-4-216-141",
          meta: { title: "资产其他指标考核质量可用性稽核管理" },
          component: Parent,
          children: [
            { path: "", redirect: "index" },
            { path: "index", name: "资产其他指标考核质量可用性稽核管理-4-216-141-main", meta: { title: "资产其他指标考核质量可用性稽核管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核质量可用性稽核管理/index") },
            { path: "KaiYuanKuangJiaZiDianXinXiGuanLi", name: "资产其他指标考核质量可用性稽核管理-4-216-141-sub1", meta: { title: "开源框架数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核质量可用性稽核管理/开源框架数据字典信息管理/index") },
            { path: "KaiYuanKuangJiaShangChuanRenWuGuanLi", name: "资产其他指标考核质量可用性稽核管理-4-216-141-sub2", meta: { title: "开源框架考核上传任务管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核质量可用性稽核管理/开源框架考核上传任务管理/index") },
            { path: "ChanPinJieMianYuYanZiDianXinXiGuanLi", name: "资产其他指标考核质量可用性稽核管理-4-216-141-sub3", meta: { title: "产品界面语言数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核质量可用性稽核管理/产品界面语言数据字典信息管理/index") },
            { path: "CaoZuoXiTongLeiXingZiDianXinXiGuanLi", name: "资产其他指标考核质量可用性稽核管理-4-216-141-sub4", meta: { title: "操作系统类型数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核质量可用性稽核管理/操作系统类型数据字典信息管理/index") },
            { path: "YingJianHuanJingZiDianXinXiGuanLi", name: "资产其他指标考核质量可用性稽核管理-4-216-141-sub5", meta: { title: "硬件环境数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核质量可用性稽核管理/硬件环境数据字典信息管理/index") },
            { path: "RuanJianHuanJingZiDianXinXiGuanLi", name: "资产其他指标考核质量可用性稽核管理-4-216-141-sub6", meta: { title: "软件环境数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核质量可用性稽核管理/软件环境数据字典信息管理/index") },
            { path: "WangLuoDanYuanLeiXingZiDianXinXiGuanLi", name: "资产其他指标考核质量可用性稽核管理-4-216-141-sub7", meta: { title: "网络单元类型数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核质量可用性稽核管理/网络单元类型数据字典信息管理/index") },
            { path: "DingJiDuiXiangMingChengZiDianXinXiGuanLi", name: "资产其他指标考核质量可用性稽核管理-4-216-141-sub8", meta: { title: "定级对象名称数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核质量可用性稽核管理/定级对象名称数据字典信息管理/index") },
            { path: "DingJiDuiXiangMingChengShangChuanRenWuGuanLi", name: "资产其他指标考核质量可用性稽核管理-4-216-141-sub9", meta: { title: "定级对象名称考核上传任务管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核质量可用性稽核管理/定级对象名称考核上传任务管理/index") },
            { path: "SuoShuAnQuanYuZiDianXinXiGuanLi", name: "资产其他指标考核质量可用性稽核管理-4-216-141-sub10", meta: { title: "所属安全域数据字典信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核质量可用性稽核管理/所属安全域数据字典信息管理/index") },
            { path: "SuoShuAnQuanYuShangChuanRenWuGuanLi", name: "资产其他指标考核质量可用性稽核管理-4-216-141-sub11", meta: { title: "所属安全域考核上传任务管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产其他指标考核质量可用性稽核管理/所属安全域考核上传任务管理/index") },
          ],
        },
{
          path: "ShuJuZhiLiangKeYongXingShenHeGongDanGuanLi",
          name: "数据质量可用性审核工单管理-4-216-142",
          meta: { title: "数据质量可用性审核工单管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/数据质量可用性审核工单管理/index"),
        },
{
          path: "ShangBaoShuJuKaoHeZhiLiangKeYongXingZhiBiaoGuanLi",
          name: "上报数据考核质量可用性指标管理-4-216-143",
          meta: { title: "上报数据考核质量可用性指标管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/上报数据考核质量可用性指标管理/index"),
        },
{
          path: "GongXinBuShangBaoShuJuKeYongXingShenPiLiuChengGuanLi",
          name: "工信部上报数据可用性审批流程管理-4-216-144",
          meta: { title: "工信部上报数据可用性审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部上报数据可用性审批流程管理/index"),
        },
{
          path: "GongXinBuKeYongHuaXiuGaiNengLiGongJu",
          name: "工信部可用化修改能力工具-4-216-145",
          meta: { title: "工信部可用化修改能力工具" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部可用化修改能力工具/index"),
        },
{
          path: "4AShangBaoShuJuDuiBiGaoJingGuiZeGuanLi",
          name: "4A上报数据对比告警规则管理-4-216-146",
          meta: { title: "4A上报数据对比告警规则管理" },
          component: Parent,
          children: [
            { path: "", redirect: "index" },
            { path: "index", name: "4A上报数据对比告警规则管理-4-216-146-main", meta: { title: "4A上报数据对比告警规则管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/index") },
            { path: "ShangBaoShuJuDuiBiGuiZeKuGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub1", meta: { title: "上报数据对比规则库管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/上报数据对比规则库管理/index") },
            { path: "4AShuJuLuRuGuiZeKuGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub2", meta: { title: "4A数据录入规则库管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/4A数据录入规则库管理/index") },
            { path: "4AShangBaoShuJuDuiBiSheZhiXinXiGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub3", meta: { title: "4A上报数据对比设置信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/4A上报数据对比设置信息管理/index") },
            { path: "4AShangBaoShuJuDuiBiCuoWuShiJianTongZhiGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub4", meta: { title: "4A上报数据对比错误事件通知管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/4A上报数据对比错误事件通知管理/index") },
            { path: "4AShangBaoShuJuDuiBiFangCuanGaiXinXiGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub5", meta: { title: "4A上报数据对比防篡改信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/4A上报数据对比防篡改信息管理/index") },
            { path: "GongXinBuYu4AShuJuDuiBiSheZhiXinXiGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub6", meta: { title: "工信部与4A数据对比设置信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/工信部与4A数据对比设置信息管理/index") },
            { path: "GongXinBuYu4AShuJuDuiBiFangCuanGaiXinXiGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub7", meta: { title: "工信部与4A数据对比防篡改信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/工信部与4A数据对比防篡改信息管理/index") },
            { path: "GongXinBuYu4AGuanXiDuiBiKuGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub8", meta: { title: "工信部与4A关系对比库管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/工信部与4A关系对比库管理/index") },
            { path: "4AYuZiChanShuJuChaYiSheZhiXinXiGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub9", meta: { title: "4A与资产数据差异设置信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/4A与资产数据差异设置信息管理/index") },
            { path: "4AZiChanShuJuChaYiFangCuanGaiXinXiGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub10", meta: { title: "4A资产数据差异防篡改信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/4A资产数据差异防篡改信息管理/index") },
            { path: "4AYuZiChanShuJuChaYiJianKongGuiZeGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub11", meta: { title: "4A与资产数据差异监控规则管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/4A与资产数据差异监控规则管理/index") },
            { path: "4AShangBaoZhiBiaoXinXiGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub12", meta: { title: "4A上报指标信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/4A上报指标信息管理/index") },
            { path: "4AZiChanShuJuChaYiHuiZongBaoBiaoGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub13", meta: { title: "4A资产数据差异汇总报表管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/4A资产数据差异汇总报表管理/index") },
            { path: "4AZiChanShuJuChaYiMingXiBaoBiaoGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub14", meta: { title: "4A资产数据差异明细报表管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/4A资产数据差异明细报表管理/index") },
            { path: "4AShangBaoZhiBiaoJianKongGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub15", meta: { title: "4A上报指标监控管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/4A上报指标监控管理/index") },
            { path: "GongXinBuYu4AShuJuDuiBiCuoWuGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub16", meta: { title: "工信部与4A数据对比错误管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/工信部与4A数据对比错误管理/index") },
            { path: "4AYuZiChanShuJuChaYiZongHeGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub17", meta: { title: "4A与资产数据差异管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/4A与资产数据差异综合管理/index") },
            { path: "4AShangBaoShuJuDuiBiZongHeGuanLi", name: "4A上报数据对比告警规则管理-4-216-146-sub18", meta: { title: "4A上报数据对比管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据对比告警规则管理/4A上报数据对比管理/index") },
          ],
        },
{
          path: "4AShangBaoShuJuShenPiLiuChengGuanLi",
          name: "4A上报数据审批流程管理-4-216-147",
          meta: { title: "4A上报数据审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报数据审批流程管理/index"),
        },
{
          path: "4AYuGongXinBuZiChanDuiBiRenWuGuanLi",
          name: "4A与工信部资产对比任务管理-4-216-148",
          meta: { title: "4A与工信部资产对比任务管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A与工信部资产对比任务管理/index"),
        },
{
          path: "4AYuGongXinBuZiChanChaYiTianBaoGuanLi",
          name: "4A与工信部资产差异填报管理-4-216-149",
          meta: { title: "4A与工信部资产差异填报管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A与工信部资产差异填报管理/index"),
        },
{
          path: "4AShangBaoZhiBiaoJiHeGuanLi",
          name: "4A上报指标稽核管理-4-216-150",
          meta: { title: "4A上报指标稽核管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报指标稽核管理/index"),
        },
{
          path: "4AShangBaoZhiBiaoJiHeLiuChengGuanLi",
          name: "4A上报指标稽核流程管理-4-216-151",
          meta: { title: "4A上报指标稽核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A上报指标稽核流程管理/index"),
        },
{
          path: "LouDongZuJianZiDongHuaCaiJiJiFengXianPaiCha",
          name: "漏洞组件自动化采集及风险排查-4-216-152",
          meta: { title: "漏洞组件自动化采集及风险排查" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/漏洞组件自动化采集及风险排查/index"),
        },
{
          path: "FengXianPaiChaShenPiLiuChengGuanLi",
          name: "风险排查审批流程管理-4-216-153",
          meta: { title: "风险排查审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/风险排查审批流程管理/index"),
        },
{
          path: "ZuJianLouDongSaoMiaoRenWuGuanLi",
          name: "组件漏洞扫描任务管理-4-216-154",
          meta: { title: "组件漏洞扫描任务管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/组件漏洞扫描任务管理/index"),
        },
{
          path: "ZiChanLouDongShuJuGuanLi",
          name: "资产漏洞数据管理-4-216-155",
          meta: { title: "资产漏洞数据管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产漏洞数据管理/index"),
        },
{
          path: "ZiChanLouDongShuJuXiaFaLiuChengGuanLi",
          name: "资产漏洞数据下发流程管理-4-216-156",
          meta: { title: "资产漏洞数据下发流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产漏洞数据下发流程管理/index"),
        },
{
          path: "ZiChanLouDongPiPeiGuanLi",
          name: "资产漏洞匹配管理-4-216-157",
          meta: { title: "资产漏洞匹配管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产漏洞匹配管理/index"),
        },
{
          path: "ZiChanLouDongZiDongHuaSaoMiaoJiHuaGuanLi",
          name: "资产漏洞自动化扫描计划管理-4-216-158",
          meta: { title: "资产漏洞自动化扫描计划管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产漏洞自动化扫描计划管理/index"),
        },
{
          path: "ZiChanLouDongShenJiPeiZhiGuanLi",
          name: "资产漏洞审计配置管理-4-216-159",
          meta: { title: "资产漏洞审计配置管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产漏洞审计配置管理/index"),
        },
{
          path: "ZiChanLouDongShenJiLiuChengGuanLi",
          name: "资产漏洞审计流程管理-4-216-160",
          meta: { title: "资产漏洞审计流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产漏洞审计流程管理/index"),
        },
{
          path: "LouDongFenXiPiPeiGuanLi",
          name: "漏洞分析匹配管理-4-216-161",
          meta: { title: "漏洞分析匹配管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/漏洞分析匹配管理/index"),
        },
{
          path: "HuLianWangBaoLouMianYiJianTanCeRenWuGuanLi",
          name: "互联网暴露面一键探测任务管理-4-216-162",
          meta: { title: "互联网暴露面一键探测任务管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/互联网暴露面一键探测任务管理/index"),
        },
{
          path: "BaoLouMianYiJianTanCeShenPiLiuChengGuanLi",
          name: "暴露面一键探测审批流程管理-4-216-163",
          meta: { title: "暴露面一键探测审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/暴露面一键探测审批流程管理/index"),
        },
{
          path: "HuLianWangBaoLouMianFengXianShangBaoJieKou",
          name: "互联网暴露面风险上报接口-4-216-164",
          meta: { title: "互联网暴露面风险上报接口" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/互联网暴露面风险上报接口/index"),
        },
{
          path: "HuLianWangBaoLouMianFengXianShangBaoLiuChengGuanLi",
          name: "互联网暴露面风险上报流程管理-4-216-165",
          meta: { title: "互联网暴露面风险上报流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/互联网暴露面风险上报流程管理/index"),
        },
{
          path: "BaoLouMianFengXianShangBaoShuJuJianKong",
          name: "暴露面风险上报数据监控-4-216-166",
          meta: { title: "暴露面风险上报数据监控" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/暴露面风险上报数据监控/index"),
        },
{
          path: "HuLianWangBaoLouMianJiTuanXiaFaShuJuJieKou",
          name: "互联网暴露面集团下发数据接口-4-216-167",
          meta: { title: "互联网暴露面集团下发数据接口" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/互联网暴露面集团下发数据接口/index"),
        },
{
          path: "BaoLouMianShuJuXiaFaJiHeLiuChengGuanLi",
          name: "暴露面数据下发稽核流程管理-4-216-168",
          meta: { title: "暴露面数据下发稽核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/暴露面数据下发稽核流程管理/index"),
        },
{
          path: "QuanDuanKouSaoMiaoRenWuGuanLi",
          name: "全端口扫描任务管理-4-216-169",
          meta: { title: "全端口扫描任务管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/全端口扫描任务管理/index"),
        },
{
          path: "QuanDuanKouSaoMiaoJieGuoShenHeLiuChengGuanLi",
          name: "全端口扫描结果审核流程管理-4-216-170",
          meta: { title: "全端口扫描结果审核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/全端口扫描结果审核流程管理/index"),
        },
{
          path: "YiJianTanCeYouJianTongZhiGaoJingGuiZeGuanLi",
          name: "一键探测邮件通知告警规则管理-4-216-171",
          meta: { title: "一键探测邮件通知告警规则管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/一键探测邮件通知告警规则管理/index"),
        },
{
          path: "BaoLouMianTanCeTongZhiRenWuGuanLi",
          name: "暴露面探测通知任务管理-4-216-172",
          meta: { title: "暴露面探测通知任务管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/暴露面探测通知任务管理/index"),
        },
{
          path: "ZiChanZongShuHuiZongBaoBiao",
          name: "资产总数汇总报表-4-216-173",
          meta: { title: "资产总数汇总报表" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产总数汇总报表/index"),
        },
{
          path: "GaoWeiDuanKouHuiZongBaoBiao",
          name: "高危端口汇总报表-4-216-174",
          meta: { title: "高危端口汇总报表" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/高危端口汇总报表/index"),
        },
{
          path: "LouBaoDuanKouHuiZongBaoBiao",
          name: "漏报端口汇总报表-4-216-175",
          meta: { title: "漏报端口汇总报表" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/漏报端口汇总报表/index"),
        },
{
          path: "WuBaoDuanKouHuiZongBaoBiao",
          name: "误报端口汇总报表-4-216-176",
          meta: { title: "误报端口汇总报表" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/误报端口汇总报表/index"),
        },
{
          path: "GaoJingBaiMingDanGuanLi",
          name: "告警白名单管理-4-216-177",
          meta: { title: "告警白名单管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/告警白名单管理/index"),
        },
{
          path: "GaoJingBaiMingDanShenHeLiuChengGuanLi",
          name: "告警白名单审核流程管理-4-216-178",
          meta: { title: "告警白名单审核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/告警白名单审核流程管理/index"),
        },
{
          path: "ShangBaoShuJuQingXiGuiZeGuanLi",
          name: "上报数据清洗规则管理-4-216-179",
          meta: { title: "上报数据清洗规则管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/上报数据清洗规则管理/index"),
        },
{
          path: "WangDuanSaoMiaoJiHeGuanLi",
          name: "网段扫描稽核管理-4-216-180",
          meta: { title: "网段扫描稽核管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/网段扫描稽核管理/index"),
        },
{
          path: "WangDuanSaoMiaoJiHeLiuChengGuanLi",
          name: "网段扫描稽核流程管理-4-216-181",
          meta: { title: "网段扫描稽核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/网段扫描稽核流程管理/index"),
        },
{
          path: "QuanDuanKouSaoMiaoJiGuanLi",
          name: "全端口扫描稽管理-4-216-182",
          meta: { title: "全端口扫描稽管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/全端口扫描稽管理/index"),
        },
{
          path: "QuanDuanKouSaoMiaoJiHeLiuChengGuanLi",
          name: "全端口扫描稽核流程管理-4-216-183",
          meta: { title: "全端口扫描稽核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/全端口扫描稽核流程管理/index"),
        },
{
          path: "ZiChanLeiXing4ACaiJiGuanLi",
          name: "资产类型4A采集管理-4-216-184",
          meta: { title: "资产类型4A采集管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产类型4A采集管理/index"),
        },
{
          path: "ZiChanLeiXing4ACaiJiJieGuoShenPiLiuChengGuanLi",
          name: "资产类型4A采集结果审批流程管理-4-216-185",
          meta: { title: "资产类型4A采集结果审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产类型4A采集结果审批流程管理/index"),
        },
{
          path: "ZiChanLeiXing4ACaiJiJieGuoShenHeGuanLi",
          name: "资产类型4A采集结果审核管理-4-216-186",
          meta: { title: "资产类型4A采集结果审核管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产类型4A采集结果审核管理/index"),
        },
{
          path: "4ATongBuZiChanHuiZongGuanLi",
          name: "4A同步资产汇总管理-4-216-187",
          meta: { title: "4A同步资产汇总管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A同步资产汇总管理/index"),
        },
{
          path: "4ADengLuZiChanXinXiGuanLi",
          name: "4A登录资产信息管理-4-216-188",
          meta: { title: "4A登录资产信息管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A登录资产信息管理/index"),
        },
{
          path: "4AZiChanDengLuXinXiShenHeLiuChengGuanLi",
          name: "4A资产登录信息审核流程管理-4-216-189",
          meta: { title: "4A资产登录信息审核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A资产登录信息审核流程管理/index"),
        },
{
          path: "4ADengLuCaiJiRenWuGuanLi",
          name: "4A登录采集任务管理-4-216-190",
          meta: { title: "4A登录采集任务管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/4A登录采集任务管理/index"),
        },
{
          path: "DengLuCaiJiRuKuGuanLi",
          name: "登录采集入库管理-4-216-191",
          meta: { title: "登录采集入库管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/登录采集入库管理/index"),
        },
{
          path: "DengLuCaiJiRuKuShenHeLiuChengGuanLi",
          name: "登录采集入库审核流程管理-4-216-192",
          meta: { title: "登录采集入库审核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/登录采集入库审核流程管理/index"),
        },
{
          path: "YuanChengSaoMiaoCaiJiGuanLi",
          name: "远程扫描采集管理-4-216-193",
          meta: { title: "远程扫描采集管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/远程扫描采集管理/index"),
        },
{
          path: "YuanChengSaoMiaoFenXiGuanLi",
          name: "远程扫描分析管理-4-216-194",
          meta: { title: "远程扫描分析管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/远程扫描分析管理/index"),
        },
{
          path: "YuanChengSaoMiaoFenXiJieGuoShenPiLiuChengGuanLi",
          name: "远程扫描分析结果审批流程管理-4-216-195",
          meta: { title: "远程扫描分析结果审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/远程扫描分析结果审批流程管理/index"),
        },
{
          path: "LiuLiangFenXiGuanLi",
          name: "流量分析管理-4-216-196",
          meta: { title: "流量分析管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/流量分析管理/index"),
        },
{
          path: "LiuLiangFenXiCaiJiRenWuGuanLi",
          name: "流量分析采集任务管理-4-216-197",
          meta: { title: "流量分析采集任务管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/流量分析采集任务管理/index"),
        },
{
          path: "LiuLiangFenXiCaiJiJieGuoHuiZongGuanLi",
          name: "流量分析采集结果汇总管理-4-216-198",
          meta: { title: "流量分析采集结果汇总管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/流量分析采集结果汇总管理/index"),
        },
{
          path: "LiuLiangFenXiCaiJiJieGuoShenHeLiuChengGuanLi",
          name: "流量分析采集结果审核流程管理-4-216-199",
          meta: { title: "流量分析采集结果审核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/流量分析采集结果审核流程管理/index"),
        },
{
          path: "LiuLiangFenXiDuiBiGuanLi",
          name: "流量分析对比管理-4-216-200",
          meta: { title: "流量分析对比管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/流量分析对比管理/index"),
        },
{
          path: "LiuLiangFenXiShiBaiMoXingGuanLi",
          name: "流量分析失败模型管理-4-216-201",
          meta: { title: "流量分析失败模型管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/流量分析失败模型管理/index"),
        },
{
          path: "ZiDongHuaShiBieJieGuoShenHeLiuChengGuanLi",
          name: "自动化识别结果审核流程管理-4-216-202",
          meta: { title: "自动化识别结果审核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/自动化识别结果审核流程管理/index"),
        },
{
          path: "LiuLiangGaoJingGuanLi",
          name: "流量告警管理-4-216-203",
          meta: { title: "流量告警管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/流量告警管理/index"),
        },
{
          path: "LiuLiangGaoJingShenHeLiuChengGuanLi",
          name: "流量告警审核流程管理-4-216-204",
          meta: { title: "流量告警审核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/流量告警审核流程管理/index"),
        },
{
          path: "ZiChanLeiXingGaoJingShuJuChuLi",
          name: "资产类型告警数据处理-4-216-205",
          meta: { title: "资产类型告警数据处理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产类型告警数据处理/index"),
        },
{
          path: "ZiChanLeiXingGaoJingShuJuChuLiShenPiLiuChengGuanLi",
          name: "资产类型告警数据处理审批流程管理-4-216-206",
          meta: { title: "资产类型告警数据处理审批流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产类型告警数据处理审批流程管理/index"),
        },
{
          path: "ZiChanLeiXingZiDongHuaShiBieGuanLi",
          name: "资产类型自动化识别管理-4-216-207",
          meta: { title: "资产类型自动化识别管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/资产类型自动化识别管理/index"),
        },
{
          path: "BoCeRenWuGuanLi",
          name: "拨测任务管理-4-216-208",
          meta: { title: "拨测任务管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/拨测任务管理/index"),
        },
{
          path: "BoCeRenWuJieGuoShenHeLiuChengGuanLi",
          name: "拨测任务结果审核流程管理-4-216-209",
          meta: { title: "拨测任务结果审核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/拨测任务结果审核流程管理/index"),
        },
{
          path: "BoCeZhouQiJiHuaGuanLi",
          name: "拨测周期计划管理-4-216-210",
          meta: { title: "拨测周期计划管理" },
          component: Parent,
          children: [
            { path: "", redirect: "index" },
            { path: "index", name: "拨测周期计划管理-4-216-210-main", meta: { title: "拨测周期计划管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/拨测周期计划管理/index") },
            { path: "ZiDongBoCeRenWuSheZhiXinXiGuanLi", name: "拨测周期计划管理-4-216-210-sub1", meta: { title: "自动拨测任务设置信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/拨测周期计划管理/自动拨测任务设置信息管理/index") },
            { path: "BoCeZhouQiJiHuaXinXiGuanLi", name: "拨测周期计划管理-4-216-210-sub2", meta: { title: "拨测周期计划管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/拨测周期计划管理/拨测周期计划管理/index") },
            { path: "BoCeFanWeiXinXiGuanLi", name: "拨测周期计划管理-4-216-210-sub3", meta: { title: "拨测范围信息管理" }, component: () => import("@/views/资产信息上报调整/YN云南COSMIC/拨测周期计划管理/拨测范围信息管理/index") },
          ],
        },
{
          path: "BoCeZhengQueLüGuanLi",
          name: "拨测正确率管理-4-216-211",
          meta: { title: "拨测正确率管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/拨测正确率管理/index"),
        },
{
          path: "BoCeZhengQueLüShenHeLiuChengGuanLi",
          name: "拨测正确率审核流程管理-4-216-212",
          meta: { title: "拨测正确率审核流程管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/拨测正确率审核流程管理/index"),
        },
{
          path: "AGENTYiJianBoCeGuanLi",
          name: "Agent一键拨测管理-4-216-213",
          meta: { title: "Agent一键拨测管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/Agent一键拨测管理/index"),
        },
{
          path: "DengLuCaiJiBoCeRenWuGuanLi",
          name: "登录采集拨测任务管理-4-216-214",
          meta: { title: "登录采集拨测任务管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/登录采集拨测任务管理/index"),
        },
{
          path: "DengLuCaiJiYiJianBoCeJianKongGuanLi",
          name: "登录采集一键拨测监控管理-4-216-215",
          meta: { title: "登录采集一键拨测监控管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/登录采集一键拨测监控管理/index"),
        },
{
          path: "GongXinBuZiChanBoCeJieGuoGuanLi",
          name: "工信部资产拨测结果管理-4-216-216",
          meta: { title: "工信部资产拨测结果管理" },
          component: () => import("@/views/资产信息上报调整/YN云南COSMIC/工信部资产拨测结果管理/index"),
        }
],
    },
      ],
    },
  ];

export default examplesRoutes;
