START TRANSACTION;

SET @ji_lin_cosmic_root_id = 'ji_lin_cosmic_root';

DELETE FROM t_sys_permission
WHERE id = @ji_lin_cosmic_root_id
   OR id LIKE 'ji\_lin\_cosmic\_%' ESCAPE '\';

INSERT INTO t_sys_permission (id, name, descripion, url, is_blank, pid, perms, type, icon, order_num, visible)
VALUES
('ji_lin_cosmic_root', 'JL吉林COSMIC功能', 'JL吉林COSMIC功能', '/JiLinCOSMICController/IPv4扫描器调度任务管理', 0, '1', 'gen:JiLinCOSMICController:IPv4扫描器调度任务管理:view', 0, '', 260, 0),
('ji_lin_cosmic_1', 'IPv4扫描器调度任务管理', 'IPv4扫描器调度任务管理', '/JiLinCOSMICController/IPv4扫描器调度任务管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:IPv4扫描器调度任务管理:view', 1, '', 1, 0),
('ji_lin_cosmic_2', 'IPv6扫描器调度任务管理', 'IPv6扫描器调度任务管理', '/JiLinCOSMICController/IPv6扫描器调度任务管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:IPv6扫描器调度任务管理:view', 1, '', 2, 0),
('ji_lin_cosmic_3', 'IP可访问信息探测管理', 'IP可访问信息探测管理', '/JiLinCOSMICController/IP可访问信息探测管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:IP可访问信息探测管理:view', 1, '', 3, 0),
('ji_lin_cosmic_4', 'IP扫描任务分发流程管理', 'IP扫描任务分发流程管理', '/JiLinCOSMICController/IP扫描任务分发流程管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:IP扫描任务分发流程管理:view', 1, '', 4, 0),
('ji_lin_cosmic_5', 'IP扫描指令下发接口', 'IP扫描指令下发接口', '/JiLinCOSMICController/IP扫描指令下发接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:IP扫描指令下发接口:view', 1, '', 5, 0),
('ji_lin_cosmic_6', 'IP扫描指令反馈接口', 'IP扫描指令反馈接口', '/JiLinCOSMICController/IP扫描指令反馈接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:IP扫描指令反馈接口:view', 1, '', 6, 0),
('ji_lin_cosmic_7', 'IP扫描指令接收管理', 'IP扫描指令接收管理', '/JiLinCOSMICController/IP扫描指令接收管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:IP扫描指令接收管理:view', 1, '', 7, 0),
('ji_lin_cosmic_8', 'IP段扫描规则管理', 'IP段扫描规则管理', '/JiLinCOSMICController/IP段扫描规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:IP段扫描规则管理:view', 1, '', 8, 0),
('ji_lin_cosmic_9', 'IP端口扫描准确性校验任务管理', 'IP端口扫描准确性校验任务管理', '/JiLinCOSMICController/IP端口扫描准确性校验任务管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:IP端口扫描准确性校验任务管理:view', 1, '', 9, 0),
('ji_lin_cosmic_10', 'IP纳管对比报表', 'IP纳管对比报表', '/JiLinCOSMICController/IP纳管对比报表', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:IP纳管对比报表:view', 1, '', 10, 0),
('ji_lin_cosmic_11', 'IP资产组件反馈接口', 'IP资产组件反馈接口', '/JiLinCOSMICController/IP资产组件反馈接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:IP资产组件反馈接口:view', 1, '', 11, 0),
('ji_lin_cosmic_12', 'SFTP传输通道监控', 'SFTP传输通道监控', '/JiLinCOSMICController/SFTP传输通道监控', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:SFTP传输通道监控:view', 1, '', 12, 0),
('ji_lin_cosmic_13', 'content文件生成任务管理', 'content文件生成任务管理', '/JiLinCOSMICController/content文件生成任务管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:content文件生成任务管理:view', 1, '', 13, 0),
('ji_lin_cosmic_14', '三方资源库管理', '三方资源库管理', '/JiLinCOSMICController/三方资源库管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:三方资源库管理:view', 1, '', 14, 0),
('ji_lin_cosmic_15', '上报任务调度管理', '上报任务调度管理', '/JiLinCOSMICController/上报任务调度管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:上报任务调度管理:view', 1, '', 15, 0),
('ji_lin_cosmic_16', '上报失败原因分析', '上报失败原因分析', '/JiLinCOSMICController/上报失败原因分析', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:上报失败原因分析:view', 1, '', 16, 0),
('ji_lin_cosmic_17', '上报结果接收接口', '上报结果接收接口', '/JiLinCOSMICController/上报结果接收接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:上报结果接收接口:view', 1, '', 17, 0),
('ji_lin_cosmic_18', '主机资产报表', '主机资产报表', '/JiLinCOSMICController/主机资产报表', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:主机资产报表:view', 1, '', 18, 0),
('ji_lin_cosmic_19', '主机资产采集管理', '主机资产采集管理', '/JiLinCOSMICController/主机资产采集管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:主机资产采集管理:view', 1, '', 19, 0),
('ji_lin_cosmic_20', '内网资产content结果反馈管理', '内网资产content结果反馈管理', '/JiLinCOSMICController/内网资产content结果反馈管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:内网资产content结果反馈管理:view', 1, '', 20, 0),
('ji_lin_cosmic_21', '内网资产识别模型管理', '内网资产识别模型管理', '/JiLinCOSMICController/内网资产识别模型管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:内网资产识别模型管理:view', 1, '', 21, 0),
('ji_lin_cosmic_22', '内网采集上报数据管理', '内网采集上报数据管理', '/JiLinCOSMICController/内网采集上报数据管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:内网采集上报数据管理:view', 1, '', 22, 0),
('ji_lin_cosmic_23', '内网采集任务接收管理', '内网采集任务接收管理', '/JiLinCOSMICController/内网采集任务接收管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:内网采集任务接收管理:view', 1, '', 23, 0),
('ji_lin_cosmic_24', '内网采集任务调度监控管理', '内网采集任务调度监控管理', '/JiLinCOSMICController/内网采集任务调度监控管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:内网采集任务调度监控管理:view', 1, '', 24, 0),
('ji_lin_cosmic_25', '内网采集指令文件管理', '内网采集指令文件管理', '/JiLinCOSMICController/内网采集指令文件管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:内网采集指令文件管理:view', 1, '', 25, 0),
('ji_lin_cosmic_26', '内网采集结果上报接口', '内网采集结果上报接口', '/JiLinCOSMICController/内网采集结果上报接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:内网采集结果上报接口:view', 1, '', 26, 0),
('ji_lin_cosmic_27', '内网采集资产模拟校验任务管理', '内网采集资产模拟校验任务管理', '/JiLinCOSMICController/内网采集资产模拟校验任务管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:内网采集资产模拟校验任务管理:view', 1, '', 27, 0),
('ji_lin_cosmic_28', '内网采集资产管理', '内网采集资产管理', '/JiLinCOSMICController/内网采集资产管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:内网采集资产管理:view', 1, '', 28, 0),
('ji_lin_cosmic_29', '办公外设资产管理', '办公外设资产管理', '/JiLinCOSMICController/办公外设资产管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:办公外设资产管理:view', 1, '', 29, 0),
('ji_lin_cosmic_30', '单IP扫描流程管理', '单IP扫描流程管理', '/JiLinCOSMICController/单IP扫描流程管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:单IP扫描流程管理:view', 1, '', 30, 0),
('ji_lin_cosmic_31', '厂商品牌型号代码管理', '厂商品牌型号代码管理', '/JiLinCOSMICController/厂商品牌型号代码管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:厂商品牌型号代码管理:view', 1, '', 31, 0),
('ji_lin_cosmic_32', '反馈资产完整性校验管理', '反馈资产完整性校验管理', '/JiLinCOSMICController/反馈资产完整性校验管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:反馈资产完整性校验管理:view', 1, '', 32, 0),
('ji_lin_cosmic_33', '反馈资产状态监控', '反馈资产状态监控', '/JiLinCOSMICController/反馈资产状态监控', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:反馈资产状态监控:view', 1, '', 33, 0),
('ji_lin_cosmic_34', '变更资产查询接口', '变更资产查询接口', '/JiLinCOSMICController/变更资产查询接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:变更资产查询接口:view', 1, '', 34, 0),
('ji_lin_cosmic_35', '处置下发工单管理', '处置下发工单管理', '/JiLinCOSMICController/处置下发工单管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:处置下发工单管理:view', 1, '', 35, 0),
('ji_lin_cosmic_36', '备案对比校验规则管理', '备案对比校验规则管理', '/JiLinCOSMICController/备案对比校验规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:备案对比校验规则管理:view', 1, '', 36, 0),
('ji_lin_cosmic_37', '备案验证结果报表', '备案验证结果报表', '/JiLinCOSMICController/备案验证结果报表', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:备案验证结果报表:view', 1, '', 37, 0),
('ji_lin_cosmic_38', '大模型资产管理', '大模型资产管理', '/JiLinCOSMICController/大模型资产管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:大模型资产管理:view', 1, '', 38, 0),
('ji_lin_cosmic_39', '存量未纳管资产管理', '存量未纳管资产管理', '/JiLinCOSMICController/存量未纳管资产管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:存量未纳管资产管理:view', 1, '', 39, 0),
('ji_lin_cosmic_40', '存量资产对比模型管理', '存量资产对比模型管理', '/JiLinCOSMICController/存量资产对比模型管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:存量资产对比模型管理:view', 1, '', 40, 0),
('ji_lin_cosmic_41', '定级对象上报库管理', '定级对象上报库管理', '/JiLinCOSMICController/定级对象上报库管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:定级对象上报库管理:view', 1, '', 41, 0),
('ji_lin_cosmic_42', '工信部内网采集联动接口', '工信部内网采集联动接口', '/JiLinCOSMICController/工信部内网采集联动接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:工信部内网采集联动接口:view', 1, '', 42, 0),
('ji_lin_cosmic_43', '工信部支持组件管理', '工信部支持组件管理', '/JiLinCOSMICController/工信部支持组件管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:工信部支持组件管理:view', 1, '', 43, 0),
('ji_lin_cosmic_44', '工信部联动扫描任务管理', '工信部联动扫描任务管理', '/JiLinCOSMICController/工信部联动扫描任务管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:工信部联动扫描任务管理:view', 1, '', 44, 0),
('ji_lin_cosmic_45', '工信部采集策略配置管理', '工信部采集策略配置管理', '/JiLinCOSMICController/工信部采集策略配置管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:工信部采集策略配置管理:view', 1, '', 45, 0),
('ji_lin_cosmic_46', '应用软件资产管理', '应用软件资产管理', '/JiLinCOSMICController/应用软件资产管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:应用软件资产管理:view', 1, '', 46, 0),
('ji_lin_cosmic_47', '待分析数据管理', '待分析数据管理', '/JiLinCOSMICController/待分析数据管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:待分析数据管理:view', 1, '', 47, 0),
('ji_lin_cosmic_48', '扫描任务动态分配规则管理', '扫描任务动态分配规则管理', '/JiLinCOSMICController/扫描任务动态分配规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:扫描任务动态分配规则管理:view', 1, '', 48, 0),
('ji_lin_cosmic_49', '扫描任务接收管理', '扫描任务接收管理', '/JiLinCOSMICController/扫描任务接收管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:扫描任务接收管理:view', 1, '', 49, 0),
('ji_lin_cosmic_50', '扫描任务日志上报接口', '扫描任务日志上报接口', '/JiLinCOSMICController/扫描任务日志上报接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:扫描任务日志上报接口:view', 1, '', 50, 0),
('ji_lin_cosmic_51', '扫描任务日志管理', '扫描任务日志管理', '/JiLinCOSMICController/扫描任务日志管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:扫描任务日志管理:view', 1, '', 51, 0),
('ji_lin_cosmic_52', '扫描探针管理', '扫描探针管理', '/JiLinCOSMICController/扫描探针管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:扫描探针管理:view', 1, '', 52, 0),
('ji_lin_cosmic_53', '扫描策略管理', '扫描策略管理', '/JiLinCOSMICController/扫描策略管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:扫描策略管理:view', 1, '', 53, 0),
('ji_lin_cosmic_54', '扫描结果上报接口', '扫描结果上报接口', '/JiLinCOSMICController/扫描结果上报接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:扫描结果上报接口:view', 1, '', 54, 0),
('ji_lin_cosmic_55', '指令上报接口', '指令上报接口', '/JiLinCOSMICController/指令上报接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:指令上报接口:view', 1, '', 55, 0),
('ji_lin_cosmic_56', '指令上报时效管理', '指令上报时效管理', '/JiLinCOSMICController/指令上报时效管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:指令上报时效管理:view', 1, '', 56, 0),
('ji_lin_cosmic_57', '指令反馈状态同步接口', '指令反馈状态同步接口', '/JiLinCOSMICController/指令反馈状态同步接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:指令反馈状态同步接口:view', 1, '', 57, 0),
('ji_lin_cosmic_58', '指令反馈超时预警管理', '指令反馈超时预警管理', '/JiLinCOSMICController/指令反馈超时预警管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:指令反馈超时预警管理:view', 1, '', 58, 0),
('ji_lin_cosmic_59', '指令接收任务调度管理', '指令接收任务调度管理', '/JiLinCOSMICController/指令接收任务调度管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:指令接收任务调度管理:view', 1, '', 59, 0),
('ji_lin_cosmic_60', '探针数据解析规则管理', '探针数据解析规则管理', '/JiLinCOSMICController/探针数据解析规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:探针数据解析规则管理:view', 1, '', 60, 0),
('ji_lin_cosmic_61', '接收状态反馈管理', '接收状态反馈管理', '/JiLinCOSMICController/接收状态反馈管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:接收状态反馈管理:view', 1, '', 61, 0),
('ji_lin_cosmic_62', '接收结果数据审查管理', '接收结果数据审查管理', '/JiLinCOSMICController/接收结果数据审查管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:接收结果数据审查管理:view', 1, '', 62, 0),
('ji_lin_cosmic_63', '数据同步管理', '数据同步管理', '/JiLinCOSMICController/数据同步管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:数据同步管理:view', 1, '', 63, 0),
('ji_lin_cosmic_64', '数据完整性校验规则管理', '数据完整性校验规则管理', '/JiLinCOSMICController/数据完整性校验规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:数据完整性校验规则管理:view', 1, '', 64, 0),
('ji_lin_cosmic_65', '文件命名与归档管理', '文件命名与归档管理', '/JiLinCOSMICController/文件命名与归档管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:文件命名与归档管理:view', 1, '', 65, 0),
('ji_lin_cosmic_66', '文件存储路径管理', '文件存储路径管理', '/JiLinCOSMICController/文件存储路径管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:文件存储路径管理:view', 1, '', 66, 0),
('ji_lin_cosmic_67', '暴露面资产未纳管预警管理', '暴露面资产未纳管预警管理', '/JiLinCOSMICController/暴露面资产未纳管预警管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:暴露面资产未纳管预警管理:view', 1, '', 67, 0),
('ji_lin_cosmic_68', '暴露面资产纳管对比任务管理', '暴露面资产纳管对比任务管理', '/JiLinCOSMICController/暴露面资产纳管对比任务管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:暴露面资产纳管对比任务管理:view', 1, '', 68, 0),
('ji_lin_cosmic_69', '暴露面资产纳管报表报表', '暴露面资产纳管报表报表', '/JiLinCOSMICController/暴露面资产纳管报表报表', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:暴露面资产纳管报表报表:view', 1, '', 69, 0),
('ji_lin_cosmic_70', '暴露面资产纳管管理', '暴露面资产纳管管理', '/JiLinCOSMICController/暴露面资产纳管管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:暴露面资产纳管管理:view', 1, '', 70, 0),
('ji_lin_cosmic_71', '模拟采集资产报表', '模拟采集资产报表', '/JiLinCOSMICController/模拟采集资产报表', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:模拟采集资产报表:view', 1, '', 71, 0),
('ji_lin_cosmic_72', '物理资产管理', '物理资产管理', '/JiLinCOSMICController/物理资产管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:物理资产管理:view', 1, '', 72, 0),
('ji_lin_cosmic_73', '特定资产组件同步接口', '特定资产组件同步接口', '/JiLinCOSMICController/特定资产组件同步接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:特定资产组件同步接口:view', 1, '', 73, 0),
('ji_lin_cosmic_74', '特定资产范围枚举管理', '特定资产范围枚举管理', '/JiLinCOSMICController/特定资产范围枚举管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:特定资产范围枚举管理:view', 1, '', 74, 0),
('ji_lin_cosmic_75', '电信设备资产管理', '电信设备资产管理', '/JiLinCOSMICController/电信设备资产管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:电信设备资产管理:view', 1, '', 75, 0),
('ji_lin_cosmic_76', '登录采集指纹管理', '登录采集指纹管理', '/JiLinCOSMICController/登录采集指纹管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:登录采集指纹管理:view', 1, '', 76, 0),
('ji_lin_cosmic_77', '相似度特征分析管理', '相似度特征分析管理', '/JiLinCOSMICController/相似度特征分析管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:相似度特征分析管理:view', 1, '', 77, 0),
('ji_lin_cosmic_78', '纳管模拟校验规则管理', '纳管模拟校验规则管理', '/JiLinCOSMICController/纳管模拟校验规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:纳管模拟校验规则管理:view', 1, '', 78, 0),
('ji_lin_cosmic_79', '组件库管理', '组件库管理', '/JiLinCOSMICController/组件库管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:组件库管理:view', 1, '', 79, 0),
('ji_lin_cosmic_80', '结果数据解析规则管理', '结果数据解析规则管理', '/JiLinCOSMICController/结果数据解析规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:结果数据解析规则管理:view', 1, '', 80, 0),
('ji_lin_cosmic_81', '结果文件与历史对比管理', '结果文件与历史对比管理', '/JiLinCOSMICController/结果文件与历史对比管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:结果文件与历史对比管理:view', 1, '', 81, 0),
('ji_lin_cosmic_82', '网络产品资产管理', '网络产品资产管理', '/JiLinCOSMICController/网络产品资产管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:网络产品资产管理:view', 1, '', 82, 0),
('ji_lin_cosmic_83', '联动指令控制管理', '联动指令控制管理', '/JiLinCOSMICController/联动指令控制管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:联动指令控制管理:view', 1, '', 83, 0),
('ji_lin_cosmic_84', '自动化采集方式验证管理', '自动化采集方式验证管理', '/JiLinCOSMICController/自动化采集方式验证管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:自动化采集方式验证管理:view', 1, '', 84, 0),
('ji_lin_cosmic_85', '自动采集对比报表管理', '自动采集对比报表管理', '/JiLinCOSMICController/自动采集对比报表管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:自动采集对比报表管理:view', 1, '', 85, 0),
('ji_lin_cosmic_86', '自定义项一致性校验管理', '自定义项一致性校验管理', '/JiLinCOSMICController/自定义项一致性校验管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:自定义项一致性校验管理:view', 1, '', 86, 0),
('ji_lin_cosmic_87', '自定义项一致性校验规则管理', '自定义项一致性校验规则管理', '/JiLinCOSMICController/自定义项一致性校验规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:自定义项一致性校验规则管理:view', 1, '', 87, 0),
('ji_lin_cosmic_88', '自定义项校验结果报表', '自定义项校验结果报表', '/JiLinCOSMICController/自定义项校验结果报表', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:自定义项校验结果报表:view', 1, '', 88, 0),
('ji_lin_cosmic_89', '虚拟资产未纳管预警管理', '虚拟资产未纳管预警管理', '/JiLinCOSMICController/虚拟资产未纳管预警管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:虚拟资产未纳管预警管理:view', 1, '', 89, 0),
('ji_lin_cosmic_90', '虚拟资产纳管对比任务管理', '虚拟资产纳管对比任务管理', '/JiLinCOSMICController/虚拟资产纳管对比任务管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:虚拟资产纳管对比任务管理:view', 1, '', 90, 0),
('ji_lin_cosmic_91', '虚拟资产纳管报表', '虚拟资产纳管报表', '/JiLinCOSMICController/虚拟资产纳管报表', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:虚拟资产纳管报表:view', 1, '', 91, 0),
('ji_lin_cosmic_92', '虚拟资产纳管验证管理', '虚拟资产纳管验证管理', '/JiLinCOSMICController/虚拟资产纳管验证管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:虚拟资产纳管验证管理:view', 1, '', 92, 0),
('ji_lin_cosmic_93', '虚拟资源使用审计管理', '虚拟资源使用审计管理', '/JiLinCOSMICController/虚拟资源使用审计管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:虚拟资源使用审计管理:view', 1, '', 93, 0),
('ji_lin_cosmic_94', '虚拟资源使用监控管理', '虚拟资源使用监控管理', '/JiLinCOSMICController/虚拟资源使用监控管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:虚拟资源使用监控管理:view', 1, '', 94, 0),
('ji_lin_cosmic_95', '虚拟资源变更审批流程管理', '虚拟资源变更审批流程管理', '/JiLinCOSMICController/虚拟资源变更审批流程管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:虚拟资源变更审批流程管理:view', 1, '', 95, 0),
('ji_lin_cosmic_96', '虚拟资源填报管理', '虚拟资源填报管理', '/JiLinCOSMICController/虚拟资源填报管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:虚拟资源填报管理:view', 1, '', 96, 0),
('ji_lin_cosmic_97', '虚拟资源异常监控', '虚拟资源异常监控', '/JiLinCOSMICController/虚拟资源异常监控', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:虚拟资源异常监控:view', 1, '', 97, 0),
('ji_lin_cosmic_98', '虚拟资源调度管理', '虚拟资源调度管理', '/JiLinCOSMICController/虚拟资源调度管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:虚拟资源调度管理:view', 1, '', 98, 0),
('ji_lin_cosmic_99', '虚拟资源配额管理', '虚拟资源配额管理', '/JiLinCOSMICController/虚拟资源配额管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:虚拟资源配额管理:view', 1, '', 99, 0),
('ji_lin_cosmic_100', '调度平台成功消息上传接口', '调度平台成功消息上传接口', '/JiLinCOSMICController/调度平台成功消息上传接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:调度平台成功消息上传接口:view', 1, '', 100, 0),
('ji_lin_cosmic_101', '资产IP纳管模拟校验任务管理', '资产IP纳管模拟校验任务管理', '/JiLinCOSMICController/资产IP纳管模拟校验任务管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产IP纳管模拟校验任务管理:view', 1, '', 101, 0),
('ji_lin_cosmic_102', '资产依赖查询接口', '资产依赖查询接口', '/JiLinCOSMICController/资产依赖查询接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产依赖查询接口:view', 1, '', 102, 0),
('ji_lin_cosmic_103', '资产分类信息同步接口', '资产分类信息同步接口', '/JiLinCOSMICController/资产分类信息同步接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产分类信息同步接口:view', 1, '', 103, 0),
('ji_lin_cosmic_104', '资产分类结构解析规则管理', '资产分类结构解析规则管理', '/JiLinCOSMICController/资产分类结构解析规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产分类结构解析规则管理:view', 1, '', 104, 0),
('ji_lin_cosmic_105', '资产发现方式一致性校验规则管理', '资产发现方式一致性校验规则管理', '/JiLinCOSMICController/资产发现方式一致性校验规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产发现方式一致性校验规则管理:view', 1, '', 105, 0),
('ji_lin_cosmic_106', '资产发现方式变更审查管理', '资产发现方式变更审查管理', '/JiLinCOSMICController/资产发现方式变更审查管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产发现方式变更审查管理:view', 1, '', 106, 0),
('ji_lin_cosmic_107', '资产变更信息管理', '资产变更信息管理', '/JiLinCOSMICController/资产变更信息管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产变更信息管理:view', 1, '', 107, 0),
('ji_lin_cosmic_108', '资产名称校验规则管理', '资产名称校验规则管理', '/JiLinCOSMICController/资产名称校验规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产名称校验规则管理:view', 1, '', 108, 0),
('ji_lin_cosmic_109', '资产型号一致性校验任务管理', '资产型号一致性校验任务管理', '/JiLinCOSMICController/资产型号一致性校验任务管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产型号一致性校验任务管理:view', 1, '', 109, 0),
('ji_lin_cosmic_110', '资产型号匹配算法管理', '资产型号匹配算法管理', '/JiLinCOSMICController/资产型号匹配算法管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产型号匹配算法管理:view', 1, '', 110, 0),
('ji_lin_cosmic_111', '资产备份规则管理', '资产备份规则管理', '/JiLinCOSMICController/资产备份规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产备份规则管理:view', 1, '', 111, 0),
('ji_lin_cosmic_112', '资产备案任务管理', '资产备案任务管理', '/JiLinCOSMICController/资产备案任务管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产备案任务管理:view', 1, '', 112, 0),
('ji_lin_cosmic_113', '资产归一化校验任务管理', '资产归一化校验任务管理', '/JiLinCOSMICController/资产归一化校验任务管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产归一化校验任务管理:view', 1, '', 113, 0),
('ji_lin_cosmic_114', '资产归属与位置校验规则管理', '资产归属与位置校验规则管理', '/JiLinCOSMICController/资产归属与位置校验规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产归属与位置校验规则管理:view', 1, '', 114, 0),
('ji_lin_cosmic_115', '资产描述冗余审查管理', '资产描述冗余审查管理', '/JiLinCOSMICController/资产描述冗余审查管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产描述冗余审查管理:view', 1, '', 115, 0),
('ji_lin_cosmic_116', '资产特征分析规则管理', '资产特征分析规则管理', '/JiLinCOSMICController/资产特征分析规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产特征分析规则管理:view', 1, '', 116, 0),
('ji_lin_cosmic_117', '资产状态预警管理', '资产状态预警管理', '/JiLinCOSMICController/资产状态预警管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产状态预警管理:view', 1, '', 117, 0),
('ji_lin_cosmic_118', '资产类别缺失报表', '资产类别缺失报表', '/JiLinCOSMICController/资产类别缺失报表', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产类别缺失报表:view', 1, '', 118, 0),
('ji_lin_cosmic_119', '资产类别自动化校验任务管理', '资产类别自动化校验任务管理', '/JiLinCOSMICController/资产类别自动化校验任务管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产类别自动化校验任务管理:view', 1, '', 119, 0),
('ji_lin_cosmic_120', '资产类型管理', '资产类型管理', '/JiLinCOSMICController/资产类型管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产类型管理:view', 1, '', 120, 0),
('ji_lin_cosmic_121', '资产纳管条目分析管理', '资产纳管条目分析管理', '/JiLinCOSMICController/资产纳管条目分析管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产纳管条目分析管理:view', 1, '', 121, 0),
('ji_lin_cosmic_122', '资产组件状态查询接口', '资产组件状态查询接口', '/JiLinCOSMICController/资产组件状态查询接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产组件状态查询接口:view', 1, '', 122, 0),
('ji_lin_cosmic_123', '资产范围查询接口', '资产范围查询接口', '/JiLinCOSMICController/资产范围查询接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产范围查询接口:view', 1, '', 123, 0),
('ji_lin_cosmic_124', '资产设备品牌管理', '资产设备品牌管理', '/JiLinCOSMICController/资产设备品牌管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:资产设备品牌管理:view', 1, '', 124, 0),
('ji_lin_cosmic_125', '边界距离计算管理', '边界距离计算管理', '/JiLinCOSMICController/边界距离计算管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:边界距离计算管理:view', 1, '', 125, 0),
('ji_lin_cosmic_126', '部侧IPv4扫描联动接口', '部侧IPv4扫描联动接口', '/JiLinCOSMICController/部侧IPv4扫描联动接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:部侧IPv4扫描联动接口:view', 1, '', 126, 0),
('ji_lin_cosmic_127', '部侧content文件管理', '部侧content文件管理', '/JiLinCOSMICController/部侧content文件管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:部侧content文件管理:view', 1, '', 127, 0),
('ji_lin_cosmic_128', '部侧上传通道管理', '部侧上传通道管理', '/JiLinCOSMICController/部侧上传通道管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:部侧上传通道管理:view', 1, '', 128, 0),
('ji_lin_cosmic_129', '部侧上报失败处置流程管理', '部侧上报失败处置流程管理', '/JiLinCOSMICController/部侧上报失败处置流程管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:部侧上报失败处置流程管理:view', 1, '', 129, 0),
('ji_lin_cosmic_130', '部侧历史上报数据分析', '部侧历史上报数据分析', '/JiLinCOSMICController/部侧历史上报数据分析', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:部侧历史上报数据分析:view', 1, '', 130, 0),
('ji_lin_cosmic_131', '部侧扫描上报数据管理', '部侧扫描上报数据管理', '/JiLinCOSMICController/部侧扫描上报数据管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:部侧扫描上报数据管理:view', 1, '', 131, 0),
('ji_lin_cosmic_132', '部侧结果上报流程管理', '部侧结果上报流程管理', '/JiLinCOSMICController/部侧结果上报流程管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:部侧结果上报流程管理:view', 1, '', 132, 0),
('ji_lin_cosmic_133', '部侧资产汇总信息管理', '部侧资产汇总信息管理', '/JiLinCOSMICController/部侧资产汇总信息管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:部侧资产汇总信息管理:view', 1, '', 133, 0),
('ji_lin_cosmic_134', '采集任务日志上报接口', '采集任务日志上报接口', '/JiLinCOSMICController/采集任务日志上报接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:采集任务日志上报接口:view', 1, '', 134, 0),
('ji_lin_cosmic_135', '采集模拟校验规则管理', '采集模拟校验规则管理', '/JiLinCOSMICController/采集模拟校验规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:采集模拟校验规则管理:view', 1, '', 135, 0),
('ji_lin_cosmic_136', '重点网络单元类型指纹管理', '重点网络单元类型指纹管理', '/JiLinCOSMICController/重点网络单元类型指纹管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:重点网络单元类型指纹管理:view', 1, '', 136, 0),
('ji_lin_cosmic_137', '重点网络单元类型资产管理', '重点网络单元类型资产管理', '/JiLinCOSMICController/重点网络单元类型资产管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:重点网络单元类型资产管理:view', 1, '', 137, 0),
('ji_lin_cosmic_138', '重点网络设备指令接收接口', '重点网络设备指令接收接口', '/JiLinCOSMICController/重点网络设备指令接收接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:重点网络设备指令接收接口:view', 1, '', 138, 0),
('ji_lin_cosmic_139', '重点网络设备指令解析规则管理', '重点网络设备指令解析规则管理', '/JiLinCOSMICController/重点网络设备指令解析规则管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:重点网络设备指令解析规则管理:view', 1, '', 139, 0),
('ji_lin_cosmic_140', '重点网络设备接收指令反馈接口', '重点网络设备接收指令反馈接口', '/JiLinCOSMICController/重点网络设备接收指令反馈接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:重点网络设备接收指令反馈接口:view', 1, '', 140, 0),
('ji_lin_cosmic_141', '重点网络设备结果上报接口', '重点网络设备结果上报接口', '/JiLinCOSMICController/重点网络设备结果上报接口', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:重点网络设备结果上报接口:view', 1, '', 141, 0),
('ji_lin_cosmic_142', '重点网络设备结果管理', '重点网络设备结果管理', '/JiLinCOSMICController/重点网络设备结果管理', 0, 'ji_lin_cosmic_root', 'gen:JiLinCOSMICController:重点网络设备结果管理:view', 1, '', 142, 0);

COMMIT;

SELECT COUNT(*) AS ji_lin_cosmic_permission_count
FROM t_sys_permission
WHERE id = @ji_lin_cosmic_root_id
   OR pid = @ji_lin_cosmic_root_id;
